/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chilli.glb color.glb intricate.glb -k -K 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ChilliCard(props) {
  const { nodes, materials } = useGLTF("/Models/ChettiCards/chilli.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex014"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card043"
            geometry={nodes.Bhai_Card043.geometry}
            material={materials["front.001"]}
          />
          <mesh
            name="Bhai_Card043_1"
            geometry={nodes.Bhai_Card043_1.geometry}
            material={materials["back.001"]}
          />
          <mesh
            name="Bhai_Cardout014"
            geometry={nodes.Bhai_Cardout014.geometry}
            material={materials["Material.077"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="Chili_Pepper_01001"
            position={[0, 0, -0.043]}
            rotation={[0.394, 0.099, 1.591]}
            scale={[0.012, 0.008, 0.008]}
          >
            <mesh
              name="Chili_Pepper_011497"
              geometry={nodes.Chili_Pepper_011497.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              name="Chili_Pepper_011497_1"
              geometry={nodes.Chili_Pepper_011497_1.geometry}
              material={materials["Material.011"]}
            />
            <mesh
              name="Chili_Pepper_011497_2"
              geometry={nodes.Chili_Pepper_011497_2.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              name="Chili_Pepper_011497_3"
              geometry={nodes.Chili_Pepper_011497_3.geometry}
              material={materials["Material.016"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chilli.glb");
