/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mortar.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

import { Context } from "../../../src/context";
export function MortarCard(props) {
  const { nodes, materials } = useGLTF("/Models/ChettiCards/mortar.glb");
  const { rot } = props;
  const group = React.useRef();
  const { speed } = React.useContext(Context);
  useFrame(() => {
    if (rot) {
      group.current.rotation.y += 0.01;
    }
  });
  useEffect(() => {
    gsap.to(group.current.rotation, {
      y: 0,
    });
  }, [rot]);
  return (
    <group {...props} ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex017"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card052"
            geometry={nodes.Bhai_Card052.geometry}
            material={materials["front.005"]}
          />
          <mesh
            name="Bhai_Card052_1"
            geometry={nodes.Bhai_Card052_1.geometry}
            material={materials["back.004"]}
          />
          <mesh
            name="Bhai_Cardout017"
            geometry={nodes.Bhai_Cardout017.geometry}
            material={materials["Material.003"]}
            scale={[1, 1.329, 1]}
          />
          <mesh
            name="mortar_and_pestle002"
            geometry={nodes.mortar_and_pestle002.geometry}
            material={materials.blinn1SG}
            position={[0, 0, -0.027]}
            rotation={[0, 0, 1.561]}
            scale={[0.05, 0.037, 0.037]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mortar.glb");
