/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 slow.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

import { Context } from "../../../src/context";
export function SlowCard(props) {
  const { nodes, materials } = useGLTF("/Models/ChettiCards/slow.glb");
  const { rot } = props;
  const group = React.useRef();
  const { speed } = React.useContext(Context);
  useFrame(() => {
    if (rot) {
      group.current.rotation.y += 0.01;
    }
  });
  useEffect(() => {
    gsap.to(group.current.rotation, {
      y: 0,
    });
  }, [rot]);
  return (
    <group {...props} ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex018"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card055"
            geometry={nodes.Bhai_Card055.geometry}
            material={materials["front.006"]}
          />
          <mesh
            name="Bhai_Card055_1"
            geometry={nodes.Bhai_Card055_1.geometry}
            material={materials["back.005"]}
          />
          <mesh
            name="Bhai_Cardout018"
            geometry={nodes.Bhai_Cardout018.geometry}
            material={materials["Material.005"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="group329809162003"
            position={[0, 0, -0.039]}
            rotation={[1.489, 0.784, -1.373]}
            scale={[0.83, 0.977, 0.977]}
          >
            <mesh
              name="group3298091625482"
              geometry={nodes.group3298091625482.geometry}
              material={materials["Plastic White 11"]}
            />
            <mesh
              name="group3298091625482_1"
              geometry={nodes.group3298091625482_1.geometry}
              material={materials.mat8}
            />
            <mesh
              name="group3298091625482_2"
              geometry={nodes.group3298091625482_2.geometry}
              material={materials["Material.004"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/slow.glb");
