/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spices.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import { Context } from "../../../src/context";

export function SpicesCard(props) {
  const { nodes, materials } = useGLTF("/Models/ChettiCards/spices.glb");
  const { rot } = props;
  const group = React.useRef();
  const { speed } = React.useContext(Context);
  useFrame(() => {
    if (rot) {
      group.current.rotation.y += 0.01;
    }
  });
  useEffect(() => {
    gsap.to(group.current.rotation, {
      y: 0,
    });
  }, [rot]);
  return (
    <group {...props} ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex016"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card049"
            geometry={nodes.Bhai_Card049.geometry}
            material={materials["front.004"]}
          />
          <mesh
            name="Bhai_Card049_1"
            geometry={nodes.Bhai_Card049_1.geometry}
            material={materials["back.003"]}
          />
          <mesh
            name="Bhai_Cardout016"
            geometry={nodes.Bhai_Cardout016.geometry}
            material={materials["Material.002"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="cinnamon_stick002"
            position={[0, 0, -0.036]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-0.076, -0.032, -0.101]}
          >
            <mesh
              name="cinnamon_stick6689"
              geometry={nodes.cinnamon_stick6689.geometry}
              material={materials["lambert2SG.012"]}
            />
            <mesh
              name="cinnamon_stick6689_1"
              geometry={nodes.cinnamon_stick6689_1.geometry}
              material={materials["lambert3SG.012"]}
            />
            <mesh
              name="cinnamon_stick6689_2"
              geometry={nodes.cinnamon_stick6689_2.geometry}
              material={materials["lambert2SG.013"]}
            />
            <mesh
              name="cinnamon_stick6689_3"
              geometry={nodes.cinnamon_stick6689_3.geometry}
              material={materials["lambert3SG.013"]}
            />
            <mesh
              name="cinnamon_stick6689_4"
              geometry={nodes.cinnamon_stick6689_4.geometry}
              material={materials["lambert4SG.006"]}
            />
            <mesh
              name="cinnamon_stick6689_5"
              geometry={nodes.cinnamon_stick6689_5.geometry}
              material={materials["lambert2SG.011"]}
            />
            <mesh
              name="cinnamon_stick6689_6"
              geometry={nodes.cinnamon_stick6689_6.geometry}
              material={materials["lambert3SG.011"]}
            />
            <mesh
              name="cinnamon_stick6689_7"
              geometry={nodes.cinnamon_stick6689_7.geometry}
              material={materials["lambert5SG.006"]}
            />
            <mesh
              name="cinnamon_stick6689_8"
              geometry={nodes.cinnamon_stick6689_8.geometry}
              material={materials["lambert4SG.007"]}
            />
            <mesh
              name="cinnamon_stick6689_9"
              geometry={nodes.cinnamon_stick6689_9.geometry}
              material={materials["lambert2SG.014"]}
            />
            <mesh
              name="cinnamon_stick6689_10"
              geometry={nodes.cinnamon_stick6689_10.geometry}
              material={materials["lambert3SG.014"]}
            />
            <mesh
              name="cinnamon_stick6689_11"
              geometry={nodes.cinnamon_stick6689_11.geometry}
              material={materials["lambert5SG.007"]}
            />
            <mesh
              name="cinnamon_stick6689_12"
              geometry={nodes.cinnamon_stick6689_12.geometry}
              material={materials["lambert2SG.015"]}
            />
            <mesh
              name="cinnamon_stick6689_13"
              geometry={nodes.cinnamon_stick6689_13.geometry}
              material={materials["lambert3SG.015"]}
            />
            <mesh
              name="cinnamon_stick6689_14"
              geometry={nodes.cinnamon_stick6689_14.geometry}
              material={materials["lambert4SG.008"]}
            />
            <mesh
              name="cinnamon_stick6689_15"
              geometry={nodes.cinnamon_stick6689_15.geometry}
              material={materials["lambert2SG.016"]}
            />
            <mesh
              name="cinnamon_stick6689_16"
              geometry={nodes.cinnamon_stick6689_16.geometry}
              material={materials["lambert3SG.016"]}
            />
            <mesh
              name="cinnamon_stick6689_17"
              geometry={nodes.cinnamon_stick6689_17.geometry}
              material={materials["lambert5SG.008"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/spices.glb");
