/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tamarind.glb -k -K 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function TamarindCard(props) {
  const { nodes, materials } = useGLTF("/Models/ChettiCards/tamarind.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex015"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card046"
            geometry={nodes.Bhai_Card046.geometry}
            material={materials["front.003"]}
          />
          <mesh
            name="Bhai_Card046_1"
            geometry={nodes.Bhai_Card046_1.geometry}
            material={materials["back.002"]}
          />
          <mesh
            name="Bhai_Cardout015"
            geometry={nodes.Bhai_Cardout015.geometry}
            material={materials["Material.001"]}
            scale={[1, 1.329, 1]}
          />
          <group name="Raisin_242002" position={[0, 0, -0.019]} scale={0.002}>
            <mesh
              name="Raisin_2421537"
              geometry={nodes.Raisin_2421537.geometry}
              material={materials["01___Default"]}
            />
            <mesh
              name="Raisin_2421537_1"
              geometry={nodes.Raisin_2421537_1.geometry}
              material={materials["mat19.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/tamarind.glb");
