/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 countries.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";
import { useFrame } from "@react-three/fiber";
gsap.registerPlugin(ScrollTrigger);

export function CountriesModel(props) {
  const { nodes, materials } = useGLTF("/Models/countries.glb");
  const mainRef = React.useRef();
  const rotRef = React.useRef();
  const [active, setActive] = React.useState(false);
  const [shouldRotate, setShouldRotate] = React.useState(true);
  // const { scale, x, y, z, Xrot } = useControls({
  //   scale: { value: 0.3, min: 0, max: 2, step: 0.01 },
  //   x: { value: 0, min: -2, max: 2, step: 0.01 },
  //   y: { value: 0, min: -2, max: 2, step: 0.01 },
  //   z: { value: 0, min: -2, max: 2, step: 0.01 },
  //   Xrot: { value: 0, min: -2, max: 2, step: 0.01 },
  // });
  useFrame(() => {
    if (active && shouldRotate)
      rotRef.current.rotation.y =
        (rotRef.current.rotation.y + 0.01) % (2 * Math.PI);
  });

  useGSAP(() => {
    gsap.fromTo(
      mainRef.current.scale,
      {
        x: 0,
        y: 0,
        z: 0,
      },
      {
        x: 0.23,
        y: 0.23,
        z: 0.23,
        duration: 0.0001,
        scrollTrigger: {
          trigger: ".food-is-culture",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          onEnter: () => {
            setActive(true);
          },
          onLeaveBack: () => {
            setActive(false);
          },
        },
      }
    );
    gsap.fromTo(
      mainRef.current.scale,
      {
        x: 0.23,
        y: 0.23,
        z: 0.23,
      },
      {
        x: 0.3,
        y: 0.3,
        z: 0.3,
        scrollTrigger: {
          trigger: ".cuisines-of-the-world-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
    gsap.fromTo(
      mainRef.current.position,
      {
        x: 0.35,
      },
      {
        x: -0.4,
        scrollTrigger: {
          trigger: ".cuisines-of-the-world-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
    gsap.fromTo(
      mainRef.current.position,
      {
        x: -0.4,
      },
      {
        x: 0.23,
        scrollTrigger: {
          trigger: ".cuisines-of-India-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
          onEnter: () => {
            setShouldRotate(false);
            gsap.to(rotRef.current.rotation, {
              y: 0,
              duration: 1,
            });
          },
          onLeaveBack: () => {
            setShouldRotate(true);
          },
        },
        immediateRender: false,
      }
    );

    gsap.fromTo(
      mainRef.current.scale,
      {
        x: 0.3,
        y: 0.3,
        z: 0.3,
      },
      {
        x: 0.71,
        y: 0.71,
        z: 0.71,
        scrollTrigger: {
          trigger: ".cuisines-of-India-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
    gsap.fromTo(
      mainRef.current.position,
      {
        x: 0.23,
        y: 0,
      },
      {
        x: 0.16,
        y: 0.17,
        scrollTrigger: {
          trigger: ".cuisines-of-TN-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
    gsap.fromTo(
      mainRef.current.scale,
      {
        x: 0.71,
        y: 0.71,
        z: 0.71,
      },
      {
        x: 1.33,
        y: 1.33,
        z: 1.33,
        scrollTrigger: {
          trigger: ".cuisines-of-TN-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
    gsap.fromTo(
      mainRef.current.rotation,
      {
        x: 0,
      },
      {
        x: -0.09,
        scrollTrigger: {
          trigger: ".cuisines-of-TN-trigger",
          start: "top bottom",
          end: "top top",
          toggleActions: "play none none reverse",
          scrub: 0.1,
        },
        immediateRender: false,
      }
    );
  });
  return (
    <group
      scale={0}
      position={[0.35, 0, 0]}
      rotation={[0, 0, 0]}
      ref={mainRef}
      dispose={null}
    >
      <group ref={rotRef}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={nodes.Sphere002.material}
          scale={1.199}
        >
          <group position={[0, 0.04, 0.963]} scale={4.025}>
            <mesh
              geometry={nodes.Plane666.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane666_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.024, -0.277, 0.948]} scale={4.025}>
            <mesh
              geometry={nodes.Plane667.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane667_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.513, 0.767, -0.296]} scale={4.025}>
            <mesh
              geometry={nodes.Plane668.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane668_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.061, 0.612, -0.623]} scale={4.025}>
            <mesh
              geometry={nodes.Plane669.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane669_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.116, 0.302, -0.876]} scale={4.025}>
            <mesh
              geometry={nodes.Plane670.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane670_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.3, 0.716, -0.604]} scale={4.025}>
            <mesh
              geometry={nodes.Plane671.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane671_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.195, 0.81, -0.527]} scale={4.025}>
            <mesh
              geometry={nodes.Plane672.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane672_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.447, -0.583, -0.582]} scale={4.025}>
            <mesh
              geometry={nodes.Plane674.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane674_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.762, -0.377, 0.451]} scale={4.025}>
            <mesh
              geometry={nodes.Plane675.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane675_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.689, 0.471, 0.509]} scale={4.025}>
            <mesh
              geometry={nodes.Plane676.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane676_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.516, 0.002, 0.824]} scale={4.025}>
            <mesh
              geometry={nodes.Plane677.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane677_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.345, -0.125, 0.903]} scale={4.025}>
            <mesh
              geometry={nodes.Plane678.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane678_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.6, -0.433, 0.653]} scale={4.025}>
            <mesh
              geometry={nodes.Plane679.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane679_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.813, 0.017, 0.465]} scale={4.025}>
            <mesh
              geometry={nodes.Plane680.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane680_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.035, -0.049, -0.951]} scale={4.025}>
            <mesh
              geometry={nodes.Plane681.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane681_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.447, 0.21, 0.838]} scale={4.025}>
            <mesh
              geometry={nodes.Plane682.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane682_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.763, 0.514, 0.345]} scale={4.025}>
            <mesh
              geometry={nodes.Plane683.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane683_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.022, 0.382, 0.843]} scale={4.025}>
            <mesh
              geometry={nodes.Plane684.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane684_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.125, 0.74, -0.64]} scale={4.025}>
            <mesh
              geometry={nodes.Plane685.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane685_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.858, 0.441, 0.2]} scale={4.025}>
            <mesh
              geometry={nodes.Plane686.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane686_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.828, 0.538, 0.024]} scale={4.025}>
            <mesh
              geometry={nodes.Plane687.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane687_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.82, -0.482, 0.268]} scale={4.025}>
            <mesh
              geometry={nodes.Plane688.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane688_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.639, 0.595, -0.463]} scale={4.025}>
            <mesh
              geometry={nodes.Plane689.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane689_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.624, -0.763, -0.07]} scale={4.025}>
            <mesh
              geometry={nodes.Plane690.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane690_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.592, -0.791, -0.024]} scale={4.025}>
            <mesh
              geometry={nodes.Plane691.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane691_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.816, 0.383, 0.404]} scale={4.025}>
            <mesh
              geometry={nodes.Plane692.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane692_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.786, 0.201, 0.564]} scale={4.025}>
            <mesh
              geometry={nodes.Plane693.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane693_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.759, 0.175, 0.608]} scale={4.025}>
            <mesh
              geometry={nodes.Plane695.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane695_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.555, -0.786, 0.226]} scale={4.025}>
            <mesh
              geometry={nodes.Plane696.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane696_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.702, 0.3, 0.625]} scale={4.025}>
            <mesh
              geometry={nodes.Plane697.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane697_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.942, 0.298, 0.006]} scale={4.025}>
            <mesh
              geometry={nodes.Plane698.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane698_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.777, -0.507, 0.335]} scale={4.025}>
            <mesh
              geometry={nodes.Plane699.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane699_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.813, 0.559, 0.064]} scale={4.025}>
            <mesh
              geometry={nodes.Plane700.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane700_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.807, 0.558, 0.103]} scale={4.025}>
            <mesh
              geometry={nodes.Plane701.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane701_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.747, 0.57, 0.306]} scale={4.025}>
            <mesh
              geometry={nodes.Plane702.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane702_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.732, -0.464, 0.472]} scale={4.025}>
            <mesh
              geometry={nodes.Plane703.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane703_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.684, -0.399, 0.591]} scale={4.025}>
            <mesh
              geometry={nodes.Plane704.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane704_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.438, -0.506, 0.725]} scale={4.025}>
            <mesh
              geometry={nodes.Plane705.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane705_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.661, -0.162, 0.716]} scale={4.025}>
            <mesh
              geometry={nodes.Plane707.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane707_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.674, -0.295, 0.66]} scale={4.025}>
            <mesh
              geometry={nodes.Plane708.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane708_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.691, -0.226, 0.669]} scale={4.025}>
            <mesh
              geometry={nodes.Plane709.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane709_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.769, 0.319, 0.53]} scale={4.025}>
            <mesh
              geometry={nodes.Plane710.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane710_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.272, -0.839, -0.446]} scale={4.025}>
            <mesh
              geometry={nodes.Plane711.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane711_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.826, 0.404, 0.351]} scale={4.025}>
            <mesh
              geometry={nodes.Plane712.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane712_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.88, 0.324, 0.312]} scale={4.025}>
            <mesh
              geometry={nodes.Plane713.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane713_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.86, 0.28, 0.398]} scale={4.025}>
            <mesh
              geometry={nodes.Plane714.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane714_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.47, -0.091, -0.864]} scale={4.025}>
            <mesh
              geometry={nodes.Plane715.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane715_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.344, -0.039, -0.923]} scale={4.025}>
            <mesh
              geometry={nodes.Plane716.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane716_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.482, 0.729, -0.462]} scale={4.025}>
            <mesh
              geometry={nodes.Plane717.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane717_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.444, 0.826, -0.312]} scale={4.025}>
            <mesh
              geometry={nodes.Plane718.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane718_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.625, 0.752, -0.14]} scale={4.025}>
            <mesh
              geometry={nodes.Plane719.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane719_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.772, 0.487, 0.375]} scale={4.025}>
            <mesh
              geometry={nodes.Plane720.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane720_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.542, 0.777, 0.281]} scale={4.025}>
            <mesh
              geometry={nodes.Plane721.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane721_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.56, 0.76, 0.291]} scale={4.025}>
            <mesh
              geometry={nodes.Plane722.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane722_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.576, 0.774, 0.22]} scale={4.025}>
            <mesh
              geometry={nodes.Plane723.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane723_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.147, 0.814, 0.54]} scale={4.025}>
            <mesh
              geometry={nodes.Plane724.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane724_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.173, 0.808, 0.542]} scale={4.025}>
            <mesh
              geometry={nodes.Plane725.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane725_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.226, 0.802, 0.531]} scale={4.025}>
            <mesh
              geometry={nodes.Plane726.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane726_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.691, 0.56, 0.431]} scale={4.025}>
            <mesh
              geometry={nodes.Plane727.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane727_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.282, 0.814, 0.484]} scale={4.025}>
            <mesh
              geometry={nodes.Plane728.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane728_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.215, 0.817, 0.513]} scale={4.025}>
            <mesh
              geometry={nodes.Plane729.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane729_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.332, 0.723, 0.587]} scale={4.025}>
            <mesh
              geometry={nodes.Plane730.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane730_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.238, 0.763, 0.58]} scale={4.025}>
            <mesh
              geometry={nodes.Plane731.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane731_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.179, 0.816, 0.529]} scale={4.025}>
            <mesh
              geometry={nodes.Plane732.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane732_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.145, 0.817, 0.537]} scale={4.025}>
            <mesh
              geometry={nodes.Plane733.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane733_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.382, 0.489, -0.769]} scale={4.025}>
            <mesh
              geometry={nodes.Plane735.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane735_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.08, 0.808, -0.563]} scale={4.025}>
            <mesh
              geometry={nodes.Plane736.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane736_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.235, 0.757, -0.589]} scale={4.025}>
            <mesh
              geometry={nodes.Plane737.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane737_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.193, 0.785, -0.568]} scale={4.025}>
            <mesh
              geometry={nodes.Plane738.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane738_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.136, 0.778, -0.593]} scale={4.025}>
            <mesh
              geometry={nodes.Plane739.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane739_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.115, 0.794, -0.577]} scale={4.025}>
            <mesh
              geometry={nodes.Plane740.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane740_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.029, 0.801, -0.578]} scale={4.025}>
            <mesh
              geometry={nodes.Plane741.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane741_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.033, 0.798, -0.582]} scale={4.025}>
            <mesh
              geometry={nodes.Plane742.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane742_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.002, 0.779, -0.608]} scale={4.025}>
            <mesh
              geometry={nodes.Plane743.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane743_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.049, 0.774, -0.612]} scale={4.025}>
            <mesh
              geometry={nodes.Plane744.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane744_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.125, 0.778, -0.594]} scale={4.025}>
            <mesh
              geometry={nodes.Plane745.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane745_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.053, 0.793, -0.587]} scale={4.025}>
            <mesh
              geometry={nodes.Plane746.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane746_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.283, 0.71, -0.626]} scale={4.025}>
            <mesh
              geometry={nodes.Plane747.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane747_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.232, 0.759, -0.589]} scale={4.025}>
            <mesh
              geometry={nodes.Plane748.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane748_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.029, 0.724, -0.672]} scale={4.025}>
            <mesh
              geometry={nodes.Plane749.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane749_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.066, 0.759, -0.63]} scale={4.025}>
            <mesh
              geometry={nodes.Plane750.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane750_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.01, 0.756, -0.636]} scale={4.025}>
            <mesh
              geometry={nodes.Plane751.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane751_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.202, 0.674, -0.693]} scale={4.025}>
            <mesh
              geometry={nodes.Plane752.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane752_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.612, 0.47, -0.617]} scale={4.025}>
            <mesh
              geometry={nodes.Plane753.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane753_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.701, 0.684, -0.124]} scale={4.025}>
            <mesh
              geometry={nodes.Plane754.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane754_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.523, 0.801, 0.248]} scale={4.025}>
            <mesh
              geometry={nodes.Plane755.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane755_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.477, 0.81, 0.303]} scale={4.025}>
            <mesh
              geometry={nodes.Plane756.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane756_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.493, 0.794, 0.322]} scale={4.025}>
            <mesh
              geometry={nodes.Plane757.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane757_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.435, 0.426, -0.777]} scale={4.025}>
            <mesh
              geometry={nodes.Plane758.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane758_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.507, -0.079, 0.845]} scale={4.025}>
            <mesh
              geometry={nodes.Plane759.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane759_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.66, 0.009, 0.735]} scale={4.025}>
            <mesh
              geometry={nodes.Plane760.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane760_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.062, 0.644, 0.444]} scale={4.025}>
            <mesh
              geometry={nodes.Plane761.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane761_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.607, -0.669, 0.386]} scale={4.025}>
            <mesh
              geometry={nodes.Plane762.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane762_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.932, -0.171, 0.134]} scale={4.025}>
            <mesh
              geometry={nodes.Plane763.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane763_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.624, -0.418, 0.6]} scale={4.025}>
            <mesh
              geometry={nodes.Plane764.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane764_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.576, -0.667, 0.41]} scale={4.025}>
            <mesh
              geometry={nodes.Plane765.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane765_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.362, 0.241, 0.821]} scale={4.025}>
            <mesh
              geometry={nodes.Plane766.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane766_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.924, 0.325, 0.102]} scale={4.025}>
            <mesh
              geometry={nodes.Plane767.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane767_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[-0.655, 0.254, 0.685]} scale={4.025}>
            <mesh
              geometry={nodes.Plane768.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane768_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.807, 0.257, 0.503]} scale={4.025}>
            <mesh
              geometry={nodes.Plane770.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane770_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.343, -0.41, 0.828]} scale={4.025}>
            <mesh
              geometry={nodes.Plane771.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane771_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.64, 0.741, -0.134]} scale={4.025}>
            <mesh
              geometry={nodes.Plane774.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane774_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group position={[0.117, 0.799, -0.57]} scale={4.025}>
            <mesh
              geometry={nodes.Plane775.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Plane775_1.geometry}
              material={materials["Material.005"]}
            />
          </group>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/countries.glb");
