/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 treasure_map.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MapModel(props) {
  const { nodes, materials } = useGLTF("/Models/treasure_map.glb");
  return (
    <group rotation={[Math.PI / 2, 0, 0]} scale={0.4} {...props}>
      <mesh geometry={nodes.VR_Map_Cube029_1.geometry} scale={1.2}>
        <meshStandardMaterial transparent opacity={0.0} />
      </mesh>
      <mesh geometry={nodes.VR_Map_Cube029_1.geometry} castShadow receiveShadow>
        <meshStandardMaterial color={"#FFCC88"} roughness={0.6} metalness={0} />
      </mesh>
      <mesh geometry={nodes.VR_Map_Cube029_2.geometry} castShadow receiveShadow>
        <meshStandardMaterial color={"#5A5A5A"} roughness={0.6} metalness={0} />
      </mesh>
      <mesh geometry={nodes.VR_Map_Cube029_3.geometry} castShadow receiveShadow>
        <meshStandardMaterial color={"#FA8C7F"} roughness={0.6} metalness={0} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/treasure_map.glb");
