/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coconut.glb -k -K 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CoconutCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/coconut.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex027"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card082"
            geometry={nodes.Bhai_Card082.geometry}
            material={materials["front.009"]}
          />
          <mesh
            name="Bhai_Card082_1"
            geometry={nodes.Bhai_Card082_1.geometry}
            material={materials["back.009"]}
          />
          <mesh
            name="Bhai_Cardout027"
            geometry={nodes.Bhai_Cardout027.geometry}
            material={materials["Material.009"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="Mesh_2378006"
            position={[0, 0, -0.022]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 0.598]}
          >
            <mesh
              name="Mesh_23783329"
              geometry={nodes.Mesh_23783329.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="Mesh_23783329_1"
              geometry={nodes.Mesh_23783329_1.geometry}
              material={materials.brownDark}
            />
            <mesh
              name="Mesh_23783329_2"
              geometry={nodes.Mesh_23783329_2.geometry}
              material={materials._defaultMat}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/coconut.glb");
