/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fast.glb -k -K 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function FastCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/fast.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex024"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card073"
            geometry={nodes.Bhai_Card073.geometry}
            material={materials["front.012"]}
          />
          <mesh
            name="Bhai_Card073_1"
            geometry={nodes.Bhai_Card073_1.geometry}
            material={materials["back.012"]}
          />
          <mesh
            name="Bhai_Cardout024"
            geometry={nodes.Bhai_Cardout024.geometry}
            material={materials["Material.017"]}
            scale={[1, 1.329, 1]}
          />
          <mesh
            name="group329809162007"
            geometry={nodes.group329809162007.geometry}
            material={materials["Automotive led lights"]}
            position={[0, 0, -0.048]}
            rotation={[1.489, 0.784, -1.373]}
            scale={[0.83, 0.977, 0.977]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fast.glb");
