/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lentils.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

export function LentilsCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/lentils.glb");
  const { rot } = props;
  const group = React.useRef();
  useFrame(() => {
    if (rot) {
      group.current.rotation.y += 0.01;
    }
  });
  useEffect(() => {
    gsap.to(group.current.rotation, {
      y: 0,
    });
  }, [rot]);
  return (
    <group {...props} ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex026"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card079"
            geometry={nodes.Bhai_Card079.geometry}
            material={materials["front.010"]}
          />
          <mesh
            name="Bhai_Card079_1"
            geometry={nodes.Bhai_Card079_1.geometry}
            material={materials["back.010"]}
          />
          <mesh
            name="Bhai_Cardout026"
            geometry={nodes.Bhai_Cardout026.geometry}
            material={materials["Material.012"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="bowl_of_cereal003"
            position={[0, 0, -0.014]}
            scale={[0.087, 0.115, 0.087]}
          >
            <mesh
              name="bowl_of_cereal5163"
              geometry={nodes.bowl_of_cereal5163.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              name="bowl_of_cereal5163_1"
              geometry={nodes.bowl_of_cereal5163_1.geometry}
              material={materials.mat19}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lentils.glb");
