/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pandicolor.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

export function PnadiColorCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/pandicolor.glb");
  const { rot } = props;
  const group = React.useRef();
  useFrame(() => {
    if (rot) {
      group.current.rotation.y += 0.01;
    }
  });
  useEffect(() => {
    gsap.to(group.current.rotation, {
      y: 0,
    });
  }, [rot]);
  return (
    <group {...props} ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex023"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card070"
            geometry={nodes.Bhai_Card070.geometry}
            material={materials["front.013"]}
          />
          <mesh
            name="Bhai_Card070_1"
            geometry={nodes.Bhai_Card070_1.geometry}
            material={materials["back.013"]}
          />
          <mesh
            name="Bhai_Cardout023"
            geometry={nodes.Bhai_Cardout023.geometry}
            material={materials["Material.018"]}
            scale={[1, 1.329, 1]}
          />
          <mesh
            name="Coin006"
            geometry={nodes.Coin006.geometry}
            material={materials["Game Gold Coin"]}
            position={[0, 0, -0.044]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.136, 0.136, 0.183]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pandicolor.glb");
