/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pepper.glb -k -K 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PepperCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/pepper.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex021"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card064"
            geometry={nodes.Bhai_Card064.geometry}
            material={materials["front.002"]}
          />
          <mesh
            name="Bhai_Card064_1"
            geometry={nodes.Bhai_Card064_1.geometry}
            material={materials["back.008"]}
          />
          <mesh
            name="Bhai_Cardout021"
            geometry={nodes.Bhai_Cardout021.geometry}
            material={materials["Material.020"]}
            scale={[1, 1.329, 1]}
          />
          <group
            name="Mesh_2378001"
            position={[0, 0, -0.029]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 0.598]}
          >
            <mesh
              name="Mesh_23783326"
              geometry={nodes.Mesh_23783326.geometry}
              material={materials.mat21}
            />
            <mesh
              name="Mesh_23783326_1"
              geometry={nodes.Mesh_23783326_1.geometry}
              material={materials.mat15}
            />
            <mesh
              name="Mesh_23783326_2"
              geometry={nodes.Mesh_23783326_2.geometry}
              material={materials.mat24}
            />
            <mesh
              name="Mesh_23783326_3"
              geometry={nodes.Mesh_23783326_3.geometry}
              material={materials.mat25}
            />
            <mesh
              name="Mesh_23783326_4"
              geometry={nodes.Mesh_23783326_4.geometry}
              material={materials.mat23}
            />
            <mesh
              name="Mesh_23783326_5"
              geometry={nodes.Mesh_23783326_5.geometry}
              material={materials.mat22}
            />
            <mesh
              name="Mesh_23783326_6"
              geometry={nodes.Mesh_23783326_6.geometry}
              material={materials.mat17}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pepper.glb");
