/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 simple.glb -k -K 
*/

import React from "react";
import { Caustics, MeshRefractionMaterial, useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { RGBELoader } from "three-stdlib";
export function SimpleCard(props) {
  const { nodes, materials } = useGLTF("/Models/PandiCards/simple.glb");
  const texture = useLoader(
    RGBELoader,
    "https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/aerodynamics_workshop_1k.hdr"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Bhai_Cardtex028"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 7.526, 10]}
        >
          <mesh
            name="Bhai_Card088"
            geometry={nodes.Bhai_Card088.geometry}
            material={materials["front.014"]}
          />
          <mesh
            name="Bhai_Card088_1"
            geometry={nodes.Bhai_Card088_1.geometry}
            material={materials["back.014"]}
          />
          <mesh
            name="Bhai_Cardout028"
            geometry={nodes.Bhai_Cardout028.geometry}
            material={materials["Material.019"]}
            scale={[1, 1.329, 1]}
          />

          <mesh
            name="Jewel_03_Circle002"
            geometry={nodes.Jewel_03_Circle002.geometry}
            // material={materials["Game Gold Coin.002"]}
            position={[0, 0, -0.061]}
            scale={[0.019, 0.026, 0.019]}
          >
            {/* for a diamond */}{" "}
            <MeshRefractionMaterial
              envMap={texture}
              toneMapped={false}
              // bounces={}
              refractionRatio={0.98}
              roughness={0}
              // metalness={1}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/simple.glb");
