/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chetti_tick.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ChettiTick(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Models/Cards/selection/chetti_tick.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    actions[names[0]].play().setLoop(1, 1);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={0.184}>
          <group name="C_tick" position={[0, -0.805, -0.54]} scale={0}>
            <mesh
              name="Curve011"
              geometry={nodes.Curve011.geometry}
              material={materials["front.019"]}
            />
            <mesh
              name="Curve011_1"
              geometry={nodes.Curve011_1.geometry}
              material={materials["back.007"]}
            />
            <mesh
              name="Curve011_2"
              geometry={nodes.Curve011_2.geometry}
              material={materials["Material.021"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chetti_tick.glb");
