/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chetti_cross1.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ChettiCross(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Models/Cards/selection/chetti_cross1.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  const { selected } = props;
  React.useEffect(() => {
    if (selected) actions[names[0]].reset().play().setLoop(1, 1);
  }, [selected]);
  return (
    <group ref={group} scale={4} position={[0, 0, 5]} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={0.188}>
          <group name="C_cross" scale={0}>
            <mesh
              name="Curve008"
              geometry={nodes.Curve008.geometry}
              material={materials["front.018"]}
            />
            <mesh
              name="Curve008_1"
              geometry={nodes.Curve008_1.geometry}
              material={materials["back.006"]}
            />
            <mesh
              name="Curve008_2"
              geometry={nodes.Curve008_2.geometry}
              material={materials["Material.019"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chetti_cross1.glb");
