/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pandi_cross1.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PandiCross(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Models/Cards/selection/pandi_cross1.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  const { selected } = props;
  useEffect(() => {
    if (selected) actions[names[0]].reset().play().setLoop(1, 1);
  }, [selected]);
  return (
    <group ref={group} scale={4} position={[0, 0, 5]} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={0.083}>
          <group name="P_cross" scale={0}>
            <mesh
              name="Curve013"
              geometry={nodes.Curve013.geometry}
              material={materials["front.020"]}
            />
            <mesh
              name="Curve013_1"
              geometry={nodes.Curve013_1.geometry}
              material={materials["back.008"]}
            />
            <mesh
              name="Curve013_2"
              geometry={nodes.Curve013_2.geometry}
              material={materials["Material.024"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pandi_cross1.glb");
