/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pandi_tick.glb -k -K 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PandiTick({ int }) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/Models/Cards/selection/pandi_tick.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    if (int) actions[names[0]].play().setLoop(1, 1);
    else actions[names[0]].reset();
  }, [int]);
  return (
    <group ref={group} position={[0, 0, 3]} scale={10} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={0.108}>
          <group name="P_tick" position={[0, -1.368, 0]} scale={0}>
            <mesh
              name="Curve006"
              geometry={nodes.Curve006.geometry}
              material={materials["front.017"]}
            />
            <mesh
              name="Curve006_1"
              geometry={nodes.Curve006_1.geometry}
              material={materials["back.005"]}
            />
            <mesh
              name="Curve006_2"
              geometry={nodes.Curve006_2.geometry}
              material={materials["Material.012"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pandi_tick.glb");
