/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 chettiColor.glb intricate.glb mortor.glb redChilly.glb slow.glb spices.glb tamarind.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ChettiColorModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Chetti/chettiColor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2717001.geometry}
        material={nodes.Mesh_2717001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <mesh
          geometry={nodes.Coin001.geometry}
          material={materials["Gold.002"]}
          position={[0, 0.039, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.136, -0.136, -0.46]}
        />
        <mesh
          geometry={nodes.Mesh_1399002.geometry}
          material={materials["Material.068"]}
          position={[-0.001, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2364002.geometry}
          material={materials["Material.067"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2384002.geometry}
          material={materials["Material.068"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2623002.geometry}
          material={materials["Material.068"]}
          position={[0.004, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/chettiColor.glb");
