/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 intricate.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function IntricateModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Chetti/intricate.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2731001.geometry}
        material={nodes.Mesh_2731001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <mesh
          geometry={nodes.Jewel_02_Circle.geometry}
          material={materials["Diamond 03"]}
          position={[0, 0.037, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.018, -0.097, -0.018]}
        />
        <mesh
          geometry={nodes.Mesh_1248002.geometry}
          material={materials["Material.070"]}
          position={[-0.001, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2381002.geometry}
          material={materials["Material.071"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2587002.geometry}
          material={materials["Material.070"]}
          position={[0, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2736002.geometry}
          material={materials["Material.070"]}
          position={[-0.01, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/intricate.glb");
