/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mortor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MortarModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Chetti/mortor.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_986002.geometry}
        material={nodes.Mesh_986002.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <mesh
          geometry={nodes.Mesh_1820002.geometry}
          material={materials["Material.060"]}
          position={[0, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2193002.geometry}
          material={materials["Material.060"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2366002.geometry}
          material={materials["Material.058"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2683001.geometry}
          material={materials["Material.060"]}
          position={[-0.013, -0.099, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.mortar_and_pestle.geometry}
          material={materials.blinn1SG}
          position={[0, 0.025, 0]}
          rotation={[-1.586, -0.014, -1.589]}
          scale={[-0.125, -0.038, -0.037]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/mortor.glb");
