/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 red chilly.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function RedChillyModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Chetti/red chilly.gltf"
  );
  return (
    <group {...props} dispose={null} scale={20}>
      <group scale={[2, 2, 0.9]}>
        <mesh
          geometry={nodes.Mesh_1024002_1.geometry}
          material={materials["Material_1024.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_2.geometry}
          material={materials["Material_2720.001"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_3.geometry}
          material={materials["Material_68.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_4.geometry}
          material={materials["Material_70.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_5.geometry}
          material={materials["Material_106.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_6.geometry}
          material={materials["Material_154.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_7.geometry}
          material={materials["Material_172.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_8.geometry}
          material={materials["Material_340.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_9.geometry}
          material={materials["Material_343.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_10.geometry}
          material={materials["Material_348.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_11.geometry}
          material={materials["Material_355.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_12.geometry}
          material={materials["Material_435.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_13.geometry}
          material={materials["Material_446.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_14.geometry}
          material={materials["Material_452.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_15.geometry}
          material={materials["Material_456.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_16.geometry}
          material={materials["Material_515.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_17.geometry}
          material={materials["Material_531.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_18.geometry}
          material={materials["Material_557.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_19.geometry}
          material={materials["Material_626.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_20.geometry}
          material={materials["Material_627.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_21.geometry}
          material={materials["Material_630.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_22.geometry}
          material={materials["Material_632.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_23.geometry}
          material={materials["Material_639.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_24.geometry}
          material={materials["Material_949.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_25.geometry}
          material={materials["Material_984.002"]}
        />
        <mesh
          geometry={nodes.Mesh_1024002_26.geometry}
          material={materials["Material_2766.001"]}
        />
        <group
          position={[0, 0.042, 0]}
          rotation={[2.078, -0.273, 1.75]}
          scale={[0.019, 0.008, 0.01]}
        >
          <mesh
            geometry={nodes.Chili_Pepper_01001_1.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_2.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_3.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_4.geometry}
            material={materials["Material.038"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_2293002.geometry}
          material={materials["Material.034"]}
          position={[-0.001, -0.04, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2361002.geometry}
          material={materials["Material.033"]}
          position={[0, -0.001, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2407002.geometry}
          material={materials["Material.034"]}
          position={[0, -0.063, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2671001.geometry}
          material={materials["Material.034"]}
          position={[-0.006, -0.098, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/red chilly.gltf");
