/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 redChilly.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { CustomChettiShaderMaterial } from "../../../../../src/components/MaterialShader";

export function RedChillyModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Chetti/redChilly.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_1024002.geometry}
        // material={nodes.Mesh_1024002.material}
        scale={[50, 50, 22.5]}
      >
        <CustomChettiShaderMaterial />
        <group
          position={[0, 0.042, 0]}
          rotation={[2.078, -0.273, 1.75]}
          scale={[0.019, 0.008, 0.01]}
        >
          <mesh
            geometry={nodes.Chili_Pepper_01001_1.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_2.geometry}
            material={materials["Material.046"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_3.geometry}
            material={materials["Material.047"]}
          />
          <mesh
            geometry={nodes.Chili_Pepper_01001_4.geometry}
            material={materials["Material.048"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_2293002.geometry}
          material={materials["Material.044"]}
          position={[-0.001, -0.04, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2361002.geometry}
          material={materials["Material.043"]}
          position={[0, -0.001, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2407002.geometry}
          material={materials["Material.044"]}
          position={[0, -0.063, 0]}
        />
        <mesh
          geometry={nodes.Mesh_2671001.geometry}
          material={materials["Material.044"]}
          position={[-0.006, -0.098, 0]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/redChilly.glb");
