/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 slow.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { CustomChettiShaderMaterial } from "../../../../../src/components/MaterialShader";

export function SlowModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Chetti/slow.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2729001.geometry}
        // material={nodes.Mesh_2729001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <CustomChettiShaderMaterial />
        <group
          position={[0, 0.038, -0.013]}
          rotation={[-2.551, -0.586, 2.162]}
          scale={[-0.83, -2.044, -2.044]}
        >
          <mesh
            geometry={nodes.group329809162046.geometry}
            material={materials["mat15.002"]}
          />
          <mesh
            geometry={nodes.group329809162046_1.geometry}
            material={materials.mat8}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1935002.geometry}
          material={materials["Material.063"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2309002.geometry}
          material={materials["Material.063"]}
          position={[-0.003, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2380002.geometry}
          material={materials["Material.062"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2623001.geometry}
          material={materials["Material.063"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/slow.glb");
