/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 spices.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SpicesModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Chetti/spices.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_983002_1.geometry}
          material={materials["Material_983.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_2.geometry}
          material={materials["Material_43.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_3.geometry}
          material={materials["Material_76.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_4.geometry}
          material={materials["Material_86.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_5.geometry}
          material={materials["Material_105.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_6.geometry}
          material={materials["Material_109.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_7.geometry}
          material={materials["Material_169.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_8.geometry}
          material={materials["Material_330.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_9.geometry}
          material={materials["Material_337.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_10.geometry}
          material={materials["Material_345.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_11.geometry}
          material={materials["Material_372.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_12.geometry}
          material={materials["Material_376.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_13.geometry}
          material={materials["Material_436.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_14.geometry}
          material={materials["Material_445.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_15.geometry}
          material={materials["Material_533.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_16.geometry}
          material={materials["Material_542.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_17.geometry}
          material={materials["Material_567.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_18.geometry}
          material={materials["Material_568.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_19.geometry}
          material={materials["Material_611.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_20.geometry}
          material={materials["Material_633.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_21.geometry}
          material={materials["Material_636.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_22.geometry}
          material={materials["Material_640.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_23.geometry}
          material={materials["Material_641.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_24.geometry}
          material={materials["Material_648.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_25.geometry}
          material={materials["Material_948.002"]}
        />
        <mesh
          geometry={nodes.Mesh_983002_26.geometry}
          material={materials["Material_2775.001"]}
        />
        <group position={[0, 0.045, -0.002]} scale={[0.076, 0.032, 0.253]}>
          <mesh
            geometry={nodes.cinnamon_stick003.geometry}
            material={materials["lambert2SG.012"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick003_1.geometry}
            material={materials["lambert3SG.012"]}
          />
        </group>
        <group
          position={[0.017, 0.05, -0.051]}
          rotation={[0.266, -0.43, 0.171]}
          scale={[0.092, 0.022, 0.21]}
        >
          <mesh
            geometry={nodes.cinnamon_stick004.geometry}
            material={materials["lambert2SG.013"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick004_1.geometry}
            material={materials["lambert3SG.013"]}
          />
        </group>
        <group
          position={[-0.019, 0.037, 0.021]}
          rotation={[3.062, 0.516, -2.996]}
          scale={[0.121, 0.024, 0.233]}
        >
          <mesh
            geometry={nodes.cinnamon_stick005.geometry}
            material={materials["lambert2SG.015"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick005_1.geometry}
            material={materials["lambert3SG.015"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_2167002.geometry}
          material={materials["Material.046"]}
          position={[-0.002, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2360002.geometry}
          material={materials["Material.045"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2567002.geometry}
          material={materials["Material.046"]}
          position={[0, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2660001.geometry}
          material={materials["Material.046"]}
          position={[0, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <group
          position={[-0.008, 0.009, -0.085]}
          rotation={[-2.605, -0.235, -1.77]}
          scale={[-0.025, -0.019, -0.057]}
        >
          <mesh
            geometry={nodes.starAnise003.geometry}
            material={materials["lambert4SG.006"]}
          />
          <mesh
            geometry={nodes.starAnise003_1.geometry}
            material={materials["lambert2SG.011"]}
          />
          <mesh
            geometry={nodes.starAnise003_2.geometry}
            material={materials["lambert3SG.011"]}
          />
          <mesh
            geometry={nodes.starAnise003_3.geometry}
            material={materials["lambert5SG.006"]}
          />
        </group>
        <group
          position={[-0.018, 0.082, 0.014]}
          rotation={[0.093, 0.027, -2.679]}
          scale={[-0.013, -0.013, -0.028]}
        >
          <mesh
            geometry={nodes.starAnise004.geometry}
            material={materials["lambert4SG.007"]}
          />
          <mesh
            geometry={nodes.starAnise004_1.geometry}
            material={materials["lambert2SG.014"]}
          />
          <mesh
            geometry={nodes.starAnise004_2.geometry}
            material={materials["lambert3SG.014"]}
          />
          <mesh
            geometry={nodes.starAnise004_3.geometry}
            material={materials["lambert5SG.007"]}
          />
        </group>
        <group
          position={[0.002, 0.028, 0.04]}
          rotation={[0.172, 0.709, -2.827]}
          scale={[-0.026, -0.015, -0.036]}
        >
          <mesh
            geometry={nodes.starAnise005.geometry}
            material={materials["lambert4SG.008"]}
          />
          <mesh
            geometry={nodes.starAnise005_1.geometry}
            material={materials["lambert2SG.016"]}
          />
          <mesh
            geometry={nodes.starAnise005_2.geometry}
            material={materials["lambert3SG.016"]}
          />
          <mesh
            geometry={nodes.starAnise005_3.geometry}
            material={materials["lambert5SG.008"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/spices.gltf");
