/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 spices.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SpicesModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Chetti/spices.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_983002.geometry}
        material={nodes.Mesh_983002.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <group position={[0, 0.045, -0.002]} scale={[0.076, 0.032, 0.253]}>
          <mesh
            geometry={nodes.cinnamon_stick003.geometry}
            material={materials["lambert2SG.012"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick003_1.geometry}
            material={materials["lambert3SG.012"]}
          />
        </group>
        <group
          position={[0.017, 0.05, -0.051]}
          rotation={[0.266, -0.43, 0.171]}
          scale={[0.092, 0.022, 0.21]}
        >
          <mesh
            geometry={nodes.cinnamon_stick004.geometry}
            material={materials["lambert2SG.013"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick004_1.geometry}
            material={materials["lambert3SG.013"]}
          />
        </group>
        <group
          position={[-0.019, 0.037, 0.021]}
          rotation={[3.062, 0.516, -2.996]}
          scale={[0.121, 0.024, 0.233]}
        >
          <mesh
            geometry={nodes.cinnamon_stick005.geometry}
            material={materials["lambert2SG.015"]}
          />
          <mesh
            geometry={nodes.cinnamon_stick005_1.geometry}
            material={materials["lambert3SG.015"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_2167002.geometry}
          material={materials["Material.056"]}
          position={[-0.002, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2360002.geometry}
          material={materials["Material.055"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2567002.geometry}
          material={materials["Material.056"]}
          position={[0, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2660001.geometry}
          material={materials["Material.056"]}
          position={[0, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <group
          position={[-0.008, 0.009, -0.085]}
          rotation={[-2.605, -0.235, -1.77]}
          scale={[-0.025, -0.019, -0.057]}
        >
          <mesh
            geometry={nodes.starAnise003.geometry}
            material={materials["lambert4SG.006"]}
          />
          <mesh
            geometry={nodes.starAnise003_1.geometry}
            material={materials["lambert2SG.011"]}
          />
          <mesh
            geometry={nodes.starAnise003_2.geometry}
            material={materials["lambert3SG.011"]}
          />
          <mesh
            geometry={nodes.starAnise003_3.geometry}
            material={materials["lambert5SG.006"]}
          />
        </group>
        <group
          position={[-0.018, 0.082, 0.014]}
          rotation={[0.093, 0.027, -2.679]}
          scale={[-0.013, -0.013, -0.028]}
        >
          <mesh
            geometry={nodes.starAnise004.geometry}
            material={materials["lambert4SG.007"]}
          />
          <mesh
            geometry={nodes.starAnise004_1.geometry}
            material={materials["lambert2SG.014"]}
          />
          <mesh
            geometry={nodes.starAnise004_2.geometry}
            material={materials["lambert3SG.014"]}
          />
          <mesh
            geometry={nodes.starAnise004_3.geometry}
            material={materials["lambert5SG.007"]}
          />
        </group>
        <group
          position={[0.002, 0.028, 0.04]}
          rotation={[0.172, 0.709, -2.827]}
          scale={[-0.026, -0.015, -0.036]}
        >
          <mesh
            geometry={nodes.starAnise005.geometry}
            material={materials["lambert4SG.008"]}
          />
          <mesh
            geometry={nodes.starAnise005_1.geometry}
            material={materials["lambert2SG.016"]}
          />
          <mesh
            geometry={nodes.starAnise005_2.geometry}
            material={materials["lambert3SG.016"]}
          />
          <mesh
            geometry={nodes.starAnise005_3.geometry}
            material={materials["lambert5SG.008"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/spices.glb");
