/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tamarind.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function TamarindModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Chetti/tamarind.gltf"
  );
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_2714001_1.geometry}
          material={materials["Material_2714.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_2.geometry}
          material={materials["Material_40.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_3.geometry}
          material={materials["Material_42.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_4.geometry}
          material={materials["Material_47.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_5.geometry}
          material={materials["Material_69.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_6.geometry}
          material={materials["Material_338.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_7.geometry}
          material={materials["Material_344.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_8.geometry}
          material={materials["Material_371.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_9.geometry}
          material={materials["Material_433.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_10.geometry}
          material={materials["Material_434.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_11.geometry}
          material={materials["Material_441.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_12.geometry}
          material={materials["Material_444.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_13.geometry}
          material={materials["Material_451.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_14.geometry}
          material={materials["Material_537.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_15.geometry}
          material={materials["Material_538.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_16.geometry}
          material={materials["Material_547.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_17.geometry}
          material={materials["Material_571.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_18.geometry}
          material={materials["Material_612.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_19.geometry}
          material={materials["Material_628.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_20.geometry}
          material={materials["Material_637.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_21.geometry}
          material={materials["Material_646.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_22.geometry}
          material={materials["Material_647.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_23.geometry}
          material={materials["Material_947.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_24.geometry}
          material={materials["Material_985.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_25.geometry}
          material={materials["Material_1009.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_26.geometry}
          material={materials["Material_1011.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_27.geometry}
          material={materials["Material_2718.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2714001_28.geometry}
          material={materials["Material_2773.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2204002.geometry}
          material={materials["Material.041"]}
          position={[0, -0.064, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2295002.geometry}
          material={materials["Material.041"]}
          position={[0, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2362002.geometry}
          material={materials["Material.040"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2736001.geometry}
          material={materials["Material.041"]}
          position={[-0.01, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <group
          position={[0, 0.024, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.002, -0.006, -0.002]}
        >
          <mesh
            geometry={nodes.Raisin_242_1.geometry}
            material={materials["01___Default"]}
          />
          <mesh
            geometry={nodes.Raisin_242_2.geometry}
            material={materials["mat19.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/tamarind.gltf");
