/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tamarind.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { CustomChettiShaderMaterial } from "../../../../../src/components/MaterialShader";

export function TamarindModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Chetti/tamarind.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2714001.geometry}
        // material={nodes.Mesh_2714001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <CustomChettiShaderMaterial />
        <mesh
          geometry={nodes.Mesh_2204002.geometry}
          material={materials["Material.051"]}
          position={[0, -0.064, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2295002.geometry}
          material={materials["Material.051"]}
          position={[0, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2362002.geometry}
          material={materials["Material.050"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2736001.geometry}
          material={materials["Material.051"]}
          position={[-0.01, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <group
          position={[0, 0.024, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.002, -0.006, -0.002]}
        >
          <mesh
            geometry={nodes.Raisin_242_1.geometry}
            material={materials["01___Default"]}
          />
          <mesh
            geometry={nodes.Raisin_242_2.geometry}
            material={materials["mat19.001"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/tamarind.glb");
