/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 voteChetti.glb -k -K 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

export function VoteChetti(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/Voting/voteChetti.glb");
  const ref = useRef();
  return (
    <group
      {...props}
      dispose={null}
      ref={ref}
      onClick={() => {
        gsap.to(ref.current.rotation, {
          duration: 1,
          y: Math.PI,
          ease: "power4.out",
          onComplete: () => {
            gsap.to(ref.current.rotation, {
              duration: 0.5,
              y: 0,
              ease: "elastic.out(1, 0.3)",
            });
          },
        });
      }}
    >
      <group name="Scene">
        <group name="Curve001" rotation={[Math.PI / 2, 0, 0]} scale={47.722}>
          <mesh
            name="Curve001_1"
            geometry={nodes.Curve001_1.geometry}
            material={materials["front.015"]}
          />
          <mesh
            name="Curve001_2"
            geometry={nodes.Curve001_2.geometry}
            material={materials["back.016"]}
          />
        </group>
        <mesh
          name="Curve"
          geometry={nodes.Curve.geometry}
          material={materials["Material.022"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={47.722}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/voteChetti.glb");
