/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 voteChetti.glb -k -K 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

export function VoteChetti(props) {
  const { selected } = props;
  const { nodes, materials } = useGLTF("/Models/Cards/Voting/voteChetti.glb");
  const ref = useRef();
  useEffect(() => {
    if (selected === "chetti") {
      gsap.to(ref.current.rotation, {
        y: Math.PI,
        duration: 0.5,
        ease: "power2.inOut",
      });
    } else {
      gsap.to(ref.current.rotation, {
        y: 0,
        duration: 0.5,
        ease: "power2.inOut",
      });
    }
  }, [selected]);

  return (
    <group {...props} dispose={null} ref={ref}>
      <group name="Scene">
        <group name="Curve001" rotation={[Math.PI / 2, 0, 0]} scale={47.722}>
          <mesh
            name="Curve001_1"
            geometry={nodes.Curve001_1.geometry}
            material={materials["front.015"]}
          />
          <mesh
            name="Curve001_2"
            geometry={nodes.Curve001_2.geometry}
            material={materials["back.016"]}
          />
        </group>
        <mesh
          name="Curve"
          geometry={nodes.Curve.geometry}
          material={materials["Material.022"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={47.722}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/voteChetti.glb");
