/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 blender.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BlenderModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/blender.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_614002_1.geometry}
          material={materials["Material_614.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_2.geometry}
          material={materials["Material_20.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_3.geometry}
          material={materials["Material_46.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_4.geometry}
          material={materials["Material_51.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_5.geometry}
          material={materials["Material_53.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_6.geometry}
          material={materials["Material_54.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_7.geometry}
          material={materials["Material_58.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_8.geometry}
          material={materials["Material_85.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_9.geometry}
          material={materials["Material_164.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_10.geometry}
          material={materials["Material_166.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_11.geometry}
          material={materials["Material_328.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_12.geometry}
          material={materials["Material_349.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_13.geometry}
          material={materials["Material_363.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_14.geometry}
          material={materials["Material_366.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_15.geometry}
          material={materials["Material_377.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_16.geometry}
          material={materials["Material_425.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_17.geometry}
          material={materials["Material_437.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_18.geometry}
          material={materials["Material_454.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_19.geometry}
          material={materials["Material_467.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_20.geometry}
          material={materials["Material_468.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_21.geometry}
          material={materials["Material_469.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_22.geometry}
          material={materials["Material_485.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_23.geometry}
          material={materials["Material_497.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_24.geometry}
          material={materials["Material_498.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_25.geometry}
          material={materials["Material_529.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_26.geometry}
          material={materials["Material_530.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_27.geometry}
          material={materials["Material_575.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_28.geometry}
          material={materials["Material_950.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_29.geometry}
          material={materials["Material_987.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_30.geometry}
          material={materials["Material_1019.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_31.geometry}
          material={materials["Material_1025.002"]}
        />
        <mesh
          geometry={nodes.Mesh_614002_32.geometry}
          material={materials["Material_2778.001"]}
        />
        <group
          position={[0, 0.009, 0.003]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.478, -1.593, -0.478]}
        >
          <mesh
            geometry={nodes.kitchenBlender_1.geometry}
            material={materials.metalMedium}
          />
          <mesh
            geometry={nodes.kitchenBlender_2.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.kitchenBlender_3.geometry}
            material={materials.glass}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1104002.geometry}
          material={materials["Material.016"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2376002.geometry}
          material={materials["Material.017"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2571002.geometry}
          material={materials["Material.016"]}
          position={[-0.003, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2641001.geometry}
          material={materials["Material.016"]}
          position={[0, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/blender.gltf");
