/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 blender.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BlenderModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/blender.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_614002.geometry}
        material={nodes.Mesh_614002.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <group
          position={[0, 0.009, 0.003]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.478, -1.593, -0.478]}
        >
          <mesh
            geometry={nodes.kitchenBlender_1.geometry}
            material={materials.metalMedium}
          />
          <mesh
            geometry={nodes.kitchenBlender_2.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.kitchenBlender_3.geometry}
            material={materials.glass}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1104002.geometry}
          material={materials["Material.026"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2376002.geometry}
          material={materials["Material.027"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2571002.geometry}
          material={materials["Material.026"]}
          position={[-0.003, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2641001.geometry}
          material={materials["Material.026"]}
          position={[0, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/blender.glb");
