/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 coconut.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CoconutModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/coconut.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_988002_1.geometry}
          material={materials["Material_988.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_2.geometry}
          material={materials["Material_62.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_3.geometry}
          material={materials["Material_65.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_4.geometry}
          material={materials["Material_66.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_5.geometry}
          material={materials["Material_71.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_6.geometry}
          material={materials["Material_77.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_7.geometry}
          material={materials["Material_107.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_8.geometry}
          material={materials["Material_108.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_9.geometry}
          material={materials["Material_110.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_10.geometry}
          material={materials["Material_113.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_11.geometry}
          material={materials["Material_335.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_12.geometry}
          material={materials["Material_353.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_13.geometry}
          material={materials["Material_373.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_14.geometry}
          material={materials["Material_440.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_15.geometry}
          material={materials["Material_462.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_16.geometry}
          material={materials["Material_483.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_17.geometry}
          material={materials["Material_514.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_18.geometry}
          material={materials["Material_516.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_19.geometry}
          material={materials["Material_616.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_20.geometry}
          material={materials["Material_619.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_21.geometry}
          material={materials["Material_623.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_22.geometry}
          material={materials["Material_634.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_23.geometry}
          material={materials["Material_642.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_24.geometry}
          material={materials["Material_963.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_25.geometry}
          material={materials["Material_966.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_26.geometry}
          material={materials["Material_995.002"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_27.geometry}
          material={materials["Material_2711.001"]}
        />
        <mesh
          geometry={nodes.Mesh_988002_28.geometry}
          material={materials["Material_2770.001"]}
        />
        <group
          position={[0.015, 0.025, -0.014]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.083, -0.278, -0.083]}
        >
          <mesh
            geometry={nodes.CoconutPalmTree022_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.CoconutPalmTree022_2.geometry}
            material={materials.brownDark}
          />
          <mesh
            geometry={nodes.CoconutPalmTree022_3.geometry}
            material={materials._defaultMat}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1403002.geometry}
          material={materials["Material.004"]}
          position={[-0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_1771002.geometry}
          material={materials["Material.004"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2378002.geometry}
          material={materials["Material.002"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2646001.geometry}
          material={materials["Material.004"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/coconut.gltf");
