/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 coconut.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CoconutModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/coconut.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_988002.geometry}
        material={nodes.Mesh_988002.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <group
          position={[0.015, 0.025, -0.014]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.083, -0.278, -0.083]}
        >
          <mesh
            geometry={nodes.CoconutPalmTree001.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            geometry={nodes.CoconutPalmTree001_1.geometry}
            material={materials["brownDark.001"]}
          />
          <mesh
            geometry={nodes.CoconutPalmTree001_2.geometry}
            material={materials["_defaultMat.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1403002.geometry}
          material={materials["Material.023"]}
          position={[-0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_1771002.geometry}
          material={materials["Material.023"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2378002.geometry}
          material={materials["Material.021"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2646001.geometry}
          material={materials["Material.023"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/coconut.glb");
