/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 fast.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { CustomPandiShaderMaterial } from "../../../../../src/components/MaterialShader";

export function FastModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/fast.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2706001.geometry}
        // material={nodes.Mesh_2706001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <CustomPandiShaderMaterial />
        <mesh
          geometry={nodes.Mesh_2371002.geometry}
          material={materials["Material.032"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2610002.geometry}
          material={materials["Material.031"]}
          position={[-0.001, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2634001.geometry}
          material={materials["Material.031"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_929002.geometry}
          material={materials["Material.031"]}
          position={[-0.001, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Pickup_Thunder001.geometry}
          material={materials.Atlas}
          position={[0, 0.04, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.13, -0.434, -0.13]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/fast.glb");
