/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 fast.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function FastModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/fast.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_2706001_1.geometry}
          material={materials["Material_2706.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_2.geometry}
          material={materials["Material_36.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_3.geometry}
          material={materials["Material_89.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_4.geometry}
          material={materials["Material_90.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_5.geometry}
          material={materials["Material_91.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_6.geometry}
          material={materials["Material_92.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_7.geometry}
          material={materials["Material_93.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_8.geometry}
          material={materials["Material_327.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_9.geometry}
          material={materials["Material_383.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_10.geometry}
          material={materials["Material_418.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_11.geometry}
          material={materials["Material_419.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_12.geometry}
          material={materials["Material_428.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_13.geometry}
          material={materials["Material_448.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_14.geometry}
          material={materials["Material_449.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_15.geometry}
          material={materials["Material_450.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_16.geometry}
          material={materials["Material_473.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_17.geometry}
          material={materials["Material_474.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_18.geometry}
          material={materials["Material_477.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_19.geometry}
          material={materials["Material_479.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_20.geometry}
          material={materials["Material_480.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_21.geometry}
          material={materials["Material_654.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_22.geometry}
          material={materials["Material_655.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_23.geometry}
          material={materials["Material_656.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_24.geometry}
          material={materials["Material_658.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_25.geometry}
          material={materials["Material_981.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_26.geometry}
          material={materials["Material_1012.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2706001_27.geometry}
          material={materials["Material_2777.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2371002.geometry}
          material={materials["Material.022"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2610002.geometry}
          material={materials["Material.021"]}
          position={[-0.001, -0.04, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2634001.geometry}
          material={materials["Material.021"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_929002.geometry}
          material={materials["Material.021"]}
          position={[-0.001, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Pickup_Thunder001.geometry}
          material={materials.Atlas}
          position={[0, 0.04, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.13, -0.434, -0.13]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/fast.gltf");
