/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 lentils.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LentilsModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/lentils.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_990002.geometry}
        // material={materials["Material.015"]}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <group
          position={[0.003, 0.031, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.087, -0.289, -0.087]}
        >
          <mesh
            geometry={nodes.bowl_of_cereal002_1.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            geometry={nodes.bowl_of_cereal002_2.geometry}
            material={materials.mat19}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1964002.geometry}
          material={materials["Material.012"]}
          position={[-0.001, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2170002.geometry}
          material={materials["Material.012"]}
          position={[0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2374002.geometry}
          material={materials["Material.011"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2640001.geometry}
          material={materials["Material.012"]}
          position={[-0.01, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/lentils.glb");
