/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 lentils.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LentilsModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/lentils.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_990002_1.geometry}
          material={materials["Material_990.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_2.geometry}
          material={materials["Material_50.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_3.geometry}
          material={materials["Material_57.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_4.geometry}
          material={materials["Material_67.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_5.geometry}
          material={materials["Material_78.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_6.geometry}
          material={materials["Material_80.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_7.geometry}
          material={materials["Material_81.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_8.geometry}
          material={materials["Material_84.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_9.geometry}
          material={materials["Material_163.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_10.geometry}
          material={materials["Material_325.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_11.geometry}
          material={materials["Material_352.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_12.geometry}
          material={materials["Material_358.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_13.geometry}
          material={materials["Material_369.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_14.geometry}
          material={materials["Material_381.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_15.geometry}
          material={materials["Material_423.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_16.geometry}
          material={materials["Material_438.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_17.geometry}
          material={materials["Material_453.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_18.geometry}
          material={materials["Material_470.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_19.geometry}
          material={materials["Material_499.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_20.geometry}
          material={materials["Material_512.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_21.geometry}
          material={materials["Material_572.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_22.geometry}
          material={materials["Material_574.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_23.geometry}
          material={materials["Material_576.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_24.geometry}
          material={materials["Material_613.002"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_25.geometry}
          material={materials["Material_2710.001"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_26.geometry}
          material={materials["Material_2712.001"]}
        />
        <mesh
          geometry={nodes.Mesh_990002_27.geometry}
          material={materials["Material_2782.001"]}
        />
        <group
          position={[0.003, 0.031, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.087, -0.289, -0.087]}
        >
          <mesh
            geometry={nodes.bowl_of_cereal002_1.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            geometry={nodes.bowl_of_cereal002_2.geometry}
            material={materials.mat19}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_1964002.geometry}
          material={materials["Material.012"]}
          position={[-0.001, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2170002.geometry}
          material={materials["Material.012"]}
          position={[0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2374002.geometry}
          material={materials["Material.011"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2640001.geometry}
          material={materials["Material.012"]}
          position={[-0.01, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/lentils.gltf");
