/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 pandi color.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PandiColorModel(props) {
  const { nodes, materials } = useGLTF(
    "/Models/Cards/new/Pandi/pandi color.gltf"
  );
  return (
    <group {...props} dispose={null} scale={20}>
      <group
        position={[0.001, 0.027, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -2, -0.6]}
      >
        <mesh
          geometry={nodes.Mesh_2713001_1.geometry}
          material={materials["Material_2713.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_2.geometry}
          material={materials["Material_12.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_3.geometry}
          material={materials["Material_97.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_4.geometry}
          material={materials["Material_101.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_5.geometry}
          material={materials["Material_102.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_6.geometry}
          material={materials["Material_117.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_7.geometry}
          material={materials["Material_118.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_8.geometry}
          material={materials["Material_142.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_9.geometry}
          material={materials["Material_148.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_10.geometry}
          material={materials["Material_149.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_11.geometry}
          material={materials["Material_323.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_12.geometry}
          material={materials["Material_324.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_13.geometry}
          material={materials["Material_329.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_14.geometry}
          material={materials["Material_384.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_15.geometry}
          material={materials["Material_399.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_16.geometry}
          material={materials["Material_427.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_17.geometry}
          material={materials["Material_464.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_18.geometry}
          material={materials["Material_481.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_19.geometry}
          material={materials["Material_482.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_20.geometry}
          material={materials["Material_488.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_21.geometry}
          material={materials["Material_518.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_22.geometry}
          material={materials["Material_520.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_23.geometry}
          material={materials["Material_526.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_24.geometry}
          material={materials["Material_579.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_25.geometry}
          material={materials["Material_583.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_26.geometry}
          material={materials["Material_586.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_27.geometry}
          material={materials["Material_587.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_28.geometry}
          material={materials["Material_588.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_29.geometry}
          material={materials["Material_589.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_30.geometry}
          material={materials["Material_594.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_31.geometry}
          material={materials["Material_649.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_32.geometry}
          material={materials["Material_959.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_33.geometry}
          material={materials["Material_962.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_34.geometry}
          material={materials["Material_996.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_35.geometry}
          material={materials["Material_1001.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2713001_36.geometry}
          material={materials["Material_2779.001"]}
        />
        <mesh
          geometry={nodes.Coin.geometry}
          material={materials["Gold.001"]}
          position={[0, 0.043, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.136, -0.136, -0.46]}
        />
        <mesh
          geometry={nodes.Mesh_1402002.geometry}
          material={materials["Material.026"]}
          position={[-0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2280002.geometry}
          material={materials["Material.026"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2369002.geometry}
          material={materials["Material.024"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2659001.geometry}
          material={materials["Material.026"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pandi color.gltf");
