/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 pepper.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { CustomPandiShaderMaterial } from "../../../../../src/components/MaterialShader";

export function PepperModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/pepper.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2708001.geometry}
        // material={nodes.Mesh_2708001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <CustomPandiShaderMaterial />
        <mesh
          geometry={nodes.Mesh_2303002.geometry}
          material={materials["Material.019"]}
          position={[-0.002, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2375002.geometry}
          material={materials["Material.018"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2506002.geometry}
          material={materials["Material.019"]}
          position={[0, -0.063, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2651001.geometry}
          material={materials["Material.019"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <group
          position={[0, 0.026, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.326, -1.088, -0.326]}
        >
          <mesh
            geometry={nodes.model002.geometry}
            material={materials["mat21.001"]}
          />
          <mesh
            geometry={nodes.model002_1.geometry}
            material={materials["mat15.001"]}
          />
          <mesh
            geometry={nodes.model002_2.geometry}
            material={materials["mat24.001"]}
          />
          <mesh
            geometry={nodes.model002_3.geometry}
            material={materials["mat25.001"]}
          />
          <mesh
            geometry={nodes.model002_4.geometry}
            material={materials["mat23.001"]}
          />
          <mesh
            geometry={nodes.model002_5.geometry}
            material={materials["mat22.001"]}
          />
          <mesh
            geometry={nodes.model002_6.geometry}
            material={materials["mat17.001"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/pepper.glb");
