/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 simple.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SimpleModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/simple.gltf");
  return (
    <group {...props} dispose={null} scale={20}>
      <group rotation={[0, 0, -Math.PI]} scale={[-2, -2, -0.6]}>
        <mesh
          geometry={nodes.Mesh_2709001_1.geometry}
          material={materials["Material_2709.001"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_2.geometry}
          material={materials["Material_14.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_3.geometry}
          material={materials["Material_18.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_4.geometry}
          material={materials["Material_19.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_5.geometry}
          material={materials["Material_34.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_6.geometry}
          material={materials["Material_95.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_7.geometry}
          material={materials["Material_100.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_8.geometry}
          material={materials["Material_145.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_9.geometry}
          material={materials["Material_146.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_10.geometry}
          material={materials["Material_156.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_11.geometry}
          material={materials["Material_322.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_12.geometry}
          material={materials["Material_362.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_13.geometry}
          material={materials["Material_401.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_14.geometry}
          material={materials["Material_430.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_15.geometry}
          material={materials["Material_475.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_16.geometry}
          material={materials["Material_493.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_17.geometry}
          material={materials["Material_495.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_18.geometry}
          material={materials["Material_522.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_19.geometry}
          material={materials["Material_523.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_20.geometry}
          material={materials["Material_592.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_21.geometry}
          material={materials["Material_593.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_22.geometry}
          material={materials["Material_597.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_23.geometry}
          material={materials["Material_944.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_24.geometry}
          material={materials["Material_982.002"]}
        />
        <mesh
          geometry={nodes.Mesh_2709001_25.geometry}
          material={materials["Material_2780.001"]}
        />
        <mesh
          geometry={nodes.Jewel_03_Circle001.geometry}
          // material={materials["Diamond 02"]}
          position={[0.002, 0.053, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.019, -0.064, -0.019]}
        >
          <meshBasicMaterial
            transparent
            attach={"material"}
            color={"#101010"}
            opacity={0.7}
          />
        </mesh>
        <mesh
          geometry={nodes.Mesh_1768002.geometry}
          material={materials["Material.029"]}
          position={[0, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2313002.geometry}
          material={materials["Material.029"]}
          position={[-0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2372002.geometry}
          material={materials["Material.028"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2632001.geometry}
          material={materials["Material.029"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/simple.gltf");
