/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 simple.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SimpleModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/new/Pandi/simple.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_2709001.geometry}
        material={nodes.Mesh_2709001.material}
        rotation={[0, 0, -Math.PI]}
        scale={[-50, -50, -14.994]}
      >
        <mesh
          geometry={nodes.Jewel_03_Circle001.geometry}
          material={materials["Diamond 02"]}
          position={[0.002, 0.053, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.019, -0.064, -0.019]}
        />
        <mesh
          geometry={nodes.Mesh_1768002.geometry}
          material={materials["Material.039"]}
          position={[0, -0.062, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2313002.geometry}
          material={materials["Material.039"]}
          position={[-0.001, -0.041, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2372002.geometry}
          material={materials["Material.038"]}
          position={[0, -0.001, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
        <mesh
          geometry={nodes.Mesh_2632001.geometry}
          material={materials["Material.039"]}
          position={[-0.006, -0.098, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1, -1, -1.501]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/simple.glb");
