/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 color.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ColorModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/Chetti/color.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Asset_62new_cards491.geometry}
        material={materials.material491}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.Asset_62new_cards386.geometry}
          material={materials.material386}
          position={[-1.89, 0, 4.852]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards387.geometry}
          material={materials.material387}
          position={[-3.005, 0, 4.852]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards388.geometry}
          material={materials.material388}
          position={[-0.286, 0, 5.572]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards389.geometry}
          material={materials.material389}
          position={[1.718, 0, 5.572]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards390.geometry}
          material={materials.material390}
          position={[-1.159, 0, 4.852]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards391.geometry}
          material={materials.material391}
          position={[-4.316, 0, 4.672]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards392.geometry}
          material={materials.material392}
          position={[2.468, 0, 5.392]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards393.geometry}
          material={materials.material393}
          position={[-2.951, 0, 5.392]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards394.geometry}
          material={materials.material394}
          position={[0.391, 0, 4.672]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards395.geometry}
          material={materials.material395}
          position={[0.839, 0, 7.158]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards396.geometry}
          material={materials.material396}
          position={[-0.909, 0, 5.392]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards397.geometry}
          material={materials.material397}
          position={[-1.328, 0, 5.392]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards398.geometry}
          material={materials.material398}
          position={[0.227, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards399.geometry}
          material={materials.material399}
          position={[-0.927, 0, 7.405]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards400.geometry}
          material={materials.material400}
          position={[0.672, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards401.geometry}
          material={materials.material401}
          position={[-3.21, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards402.geometry}
          material={materials.material402}
          position={[-0.542, 0, 7.404]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards403.geometry}
          material={materials.material403}
          position={[0.338, 0, 7.404]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards404.geometry}
          material={materials.material404}
          position={[1.251, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards405.geometry}
          material={materials.material405}
          position={[3.853, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards406.geometry}
          material={materials.material406}
          position={[4.602, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards407.geometry}
          material={materials.material407}
          position={[3.308, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards408.geometry}
          material={materials.material408}
          position={[2.559, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards409.geometry}
          material={materials.material409}
          position={[-2.649, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards410.geometry}
          material={materials.material410}
          position={[3.09, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards411.geometry}
          material={materials.material411}
          position={[3.476, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards412.geometry}
          material={materials.material412}
          position={[-4.316, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards413.geometry}
          material={materials.material413}
          position={[0.391, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards414.geometry}
          material={materials.material414}
          position={[2.469, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards415.geometry}
          material={materials.material415}
          position={[-2.951, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards416.geometry}
          material={materials.material416}
          position={[-1.328, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards417.geometry}
          material={materials.material417}
          position={[0.839, 0, 7.404]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards418.geometry}
          material={materials.material418}
          position={[-0.909, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards419.geometry}
          material={materials.material419}
          position={[2.3, 0, 4.852]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards420.geometry}
          material={materials.material420}
          position={[0.079, 0, 7.337]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards421.geometry}
          material={materials.material421}
          position={[0.854, 0, 3.633]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards422.geometry}
          material={materials.material422}
          position={[-0.516, 0, 3.633]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards423.geometry}
          material={materials.material423}
          position={[-1.273, 0, 7.266]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards424.geometry}
          material={materials.material424}
          position={[-4.602, 0, 4.78]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards425.geometry}
          material={materials.material425}
          position={[0.151, 0, 4.911]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards426.geometry}
          material={materials.material426}
          position={[1.32, 0, 7.434]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards427.geometry}
          material={materials.material427}
          position={[-2.395, 0, 5.669]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards428.geometry}
          material={materials.material428}
          position={[0.227, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards429.geometry}
          material={materials.material429}
          position={[-0.927, 0, 7.404]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards430.geometry}
          material={materials.material430}
          position={[-0.516, 0, 3.632]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards431.geometry}
          material={materials.material431}
          position={[0.854, 0, 3.632]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards432.geometry}
          material={materials.material432}
          position={[0.951, 0, 4.89]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards433.geometry}
          material={materials.material433}
          position={[-2.189, 0, 4.89]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards434.geometry}
          material={materials.material434}
          position={[-3.304, 0, 4.89]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards435.geometry}
          material={materials.material435}
          position={[0.639, 0, 7.375]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards436.geometry}
          material={materials.material436}
          position={[-4.097, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards437.geometry}
          material={materials.material437}
          position={[-1.942, 0, 5.64]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards438.geometry}
          material={materials.material438}
          position={[-0.844, 0, 4.92]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards439.geometry}
          material={materials.material439}
          position={[-2.732, 0, 5.64]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards440.geometry}
          material={materials.material440}
          position={[0.944, 0, 5.579]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards441.geometry}
          material={materials.material441}
          position={[-1.49, 0, 3.531]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards442.geometry}
          material={materials.material442}
          position={[-0.297, 0, 5.635]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards443.geometry}
          material={materials.material443}
          position={[1.706, 0, 5.635]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards444.geometry}
          material={materials.material444}
          position={[-3.016, 0, 4.914]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards445.geometry}
          material={materials.material445}
          position={[-1.901, 0, 4.914]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards446.geometry}
          material={materials.material446}
          position={[-1.17, 0, 4.914]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards447.geometry}
          material={materials.material447}
          position={[1.632, 0, 4.9]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards448.geometry}
          material={materials.material448}
          position={[4.234, 0, 4.9]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards449.geometry}
          material={materials.material449}
          position={[2.941, 0, 4.9]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards450.geometry}
          material={materials.material450}
          position={[-1.582, 0, 5.658]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards451.geometry}
          material={materials.material451}
          position={[2.723, 0, 5.62]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards452.geometry}
          material={materials.material452}
          position={[-0.176, 0, 7.423]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards453.geometry}
          material={materials.material453}
          position={[-0.654, 0, 5.62]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards454.geometry}
          material={materials.material454}
          position={[-3.76, 0, 4.869]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards455.geometry}
          material={materials.material455}
          position={[1.333, 0, 5.59]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards456.geometry}
          material={materials.material456}
          position={[-1.297, 0, 7.302]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards457.geometry}
          material={materials.material457}
          position={[0.166, 0, 3.587]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards458.geometry}
          material={materials.material458}
          position={[2.576, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards459.geometry}
          material={materials.material459}
          position={[1.267, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards460.geometry}
          material={materials.material460}
          position={[3.869, 0, 4.919]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards461.geometry}
          material={materials.material461}
          position={[0.354, 0, 7.404]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards462.geometry}
          material={materials.material462}
          position={[3.106, 0, 5.639]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards463.geometry}
          material={materials.material463}
          position={[0.641, 0, 4.891]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards464.geometry}
          material={materials.material464}
          position={[3.507, 0, 5.611]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards465.geometry}
          material={materials.material465}
          position={[3.339, 0, 4.891]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards466.geometry}
          material={materials.material466}
          position={[4.633, 0, 4.891]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards467.geometry}
          material={materials.material467}
          position={[-2.618, 0, 4.891]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards468.geometry}
          material={materials.material468}
          position={[-0.573, 0, 7.433]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards469.geometry}
          material={materials.material469}
          position={[-3.241, 0, 5.668]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards470.geometry}
          material={materials.material470}
          position={[1.602, 0, 3.562]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards471.geometry}
          material={materials.material471}
          position={[-3.545, 0, 5.643]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards472.geometry}
          material={materials.material472}
          position={[-1.117, 0, 5.643]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards473.geometry}
          material={materials.material473}
          position={[-0.284, 0, 4.923]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards474.geometry}
          material={materials.material474}
          position={[0.001, 0, 0.117]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards475.geometry}
          material={materials.material475}
          position={[0.001, 0, 0.117]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards476.geometry}
          material={materials.material476}
          position={[0.001, 0, 0.116]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards477.geometry}
          material={materials.material477}
          position={[-4.603, 0, 4.855]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards478.geometry}
          material={materials.material478}
          position={[1.933, 0, 4.893]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards479.geometry}
          material={materials.material479}
          position={[2.008, 0, 5.613]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards480.geometry}
          material={materials.material480}
          position={[2.259, 0, 5.613]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards481.geometry}
          material={materials.material481}
          position={[-0.549, 0, 4.893]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards482.geometry}
          material={materials.material482}
          position={[1.035, 0, 7.378]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards483.geometry}
          material={materials.material483}
          position={[0.521, 0, 5.533]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards484.geometry}
          material={materials.material484}
          position={[-1.528, 0, 4.83]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards485.geometry}
          material={materials.material485}
          position={[-1.467, 0, 8.69]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards486.geometry}
          material={materials.material486}
          position={[0.001, 0, 8.69]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards487.geometry}
          material={materials.material487}
          position={[-2.934, 0, 8.69]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards488.geometry}
          material={materials.material488}
          position={[1.468, 0, 8.69]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards489.geometry}
          material={materials.material489}
          position={[2.936, 0, 8.69]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards490.geometry}
          material={materials.material490}
          position={[2.936, 0, 8.69]}
        />
      </mesh>
      <mesh
        geometry={nodes.Jewel_02_Circle.geometry}
        material={materials.Red_Jewel02}
        position={[0, 3.5, 0]}
        rotation={[1.44, 0, 0]}
        scale={1.19}
      />
    </group>
  );
}

useGLTF.preload("/color.gltf");
