/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 mortar.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MortarModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/Chetti/mortar.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Asset_62new_cards1002.geometry}
        material={materials.material1002}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-1}
      >
        <mesh
          geometry={nodes.Asset_62new_cards1000.geometry}
          material={materials.material1000}
          position={[2.934, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards1001.geometry}
          material={materials.material1001}
          position={[-0.001, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards857.geometry}
          material={materials.material857}
          position={[5.149, 0, 4.896]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards858.geometry}
          material={materials.material858}
          position={[-0.37, 0, 4.896]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards859.geometry}
          material={materials.material859}
          position={[2.939, 0, 5.616]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards860.geometry}
          material={materials.material860}
          position={[-4.724, 0, 5.616]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards861.geometry}
          material={materials.material861}
          position={[3.076, 0, 3.582]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards862.geometry}
          material={materials.material862}
          position={[5.954, 0, 3.582]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards863.geometry}
          material={materials.material863}
          position={[2.867, 0, 4.716]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards864.geometry}
          material={materials.material864}
          position={[-3.969, 0, 4.716]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards865.geometry}
          material={materials.material865}
          position={[1.963, 0, 4.716]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards866.geometry}
          material={materials.material866}
          position={[4.578, 0, 4.716]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards867.geometry}
          material={materials.material867}
          position={[-4.374, 0, 4.716]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards868.geometry}
          material={materials.material868}
          position={[3.8, 0, 5.436]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards869.geometry}
          material={materials.material869}
          position={[4.271, 0, 5.436]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards870.geometry}
          material={materials.material870}
          position={[-2.685, 0, 5.436]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards871.geometry}
          material={materials.material871}
          position={[0.837, 0, 7.202]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards872.geometry}
          material={materials.material872}
          position={[-0.443, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards873.geometry}
          material={materials.material873}
          position={[-0.929, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards874.geometry}
          material={materials.material874}
          position={[-2.036, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards875.geometry}
          material={materials.material875}
          position={[-1.674, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards876.geometry}
          material={materials.material876}
          position={[0.737, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards877.geometry}
          material={materials.material877}
          position={[-3.71, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards878.geometry}
          material={materials.material878}
          position={[4.319, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards879.geometry}
          material={materials.material879}
          position={[-0.544, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards880.geometry}
          material={materials.material880}
          position={[2.586, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards881.geometry}
          material={materials.material881}
          position={[1.032, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards882.geometry}
          material={materials.material882}
          position={[-4.655, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards883.geometry}
          material={materials.material883}
          position={[-5.042, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards884.geometry}
          material={materials.material884}
          position={[-2.985, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards885.geometry}
          material={materials.material885}
          position={[-0.015, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards886.geometry}
          material={materials.material886}
          position={[1.463, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards887.geometry}
          material={materials.material887}
          position={[3.488, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards888.geometry}
          material={materials.material888}
          position={[1.577, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards889.geometry}
          material={materials.material889}
          position={[0.283, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards890.geometry}
          material={materials.material890}
          position={[-2.063, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards891.geometry}
          material={materials.material891}
          position={[0.336, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards892.geometry}
          material={materials.material892}
          position={[-3.645, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards893.geometry}
          material={materials.material893}
          position={[-1.141, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards894.geometry}
          material={materials.material894}
          position={[-4.374, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards895.geometry}
          material={materials.material895}
          position={[-3.968, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards896.geometry}
          material={materials.material896}
          position={[4.578, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards897.geometry}
          material={materials.material897}
          position={[2.867, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards898.geometry}
          material={materials.material898}
          position={[1.964, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards899.geometry}
          material={materials.material899}
          position={[0.837, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards900.geometry}
          material={materials.material900}
          position={[3.8, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards901.geometry}
          material={materials.material901}
          position={[4.271, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards902.geometry}
          material={materials.material902}
          position={[-2.685, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards903.geometry}
          material={materials.material903}
          position={[-1.416, 0, 4.896]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards904.geometry}
          material={materials.material904}
          position={[-2.704, 0, 4.896]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards905.geometry}
          material={materials.material905}
          position={[0.077, 0, 7.381]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards906.geometry}
          material={materials.material906}
          position={[1.037, 0, 3.677]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards907.geometry}
          material={materials.material907}
          position={[-4.77, 0, 3.677]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards908.geometry}
          material={materials.material908}
          position={[-1.275, 0, 7.309]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards909.geometry}
          material={materials.material909}
          position={[-2.486, 0, 3.789]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards910.geometry}
          material={materials.material910}
          position={[-0.653, 0, 3.789]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards911.geometry}
          material={materials.material911}
          position={[2.229, 0, 3.461]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards912.geometry}
          material={materials.material912}
          position={[5.665, 0, 5.1]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards913.geometry}
          material={materials.material913}
          position={[-0.775, 0, 5.675]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards914.geometry}
          material={materials.material914}
          position={[-5.562, 0, 4.838]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards915.geometry}
          material={materials.material915}
          position={[1.318, 0, 7.478]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards916.geometry}
          material={materials.material916}
          position={[4.753, 0, 5.713]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards917.geometry}
          material={materials.material917}
          position={[-0.443, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards918.geometry}
          material={materials.material918}
          position={[-0.929, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards919.geometry}
          material={materials.material919}
          position={[-2.036, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards920.geometry}
          material={materials.material920}
          position={[-1.674, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards921.geometry}
          material={materials.material921}
          position={[-3.711, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards922.geometry}
          material={materials.material922}
          position={[0.737, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards923.geometry}
          material={materials.material923}
          position={[-4.77, 0, 3.676]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards924.geometry}
          material={materials.material924}
          position={[1.764, 0, 4.934]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards925.geometry}
          material={materials.material925}
          position={[1.015, 0, 4.934]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards926.geometry}
          material={materials.material926}
          position={[-5.341, 0, 4.934]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards927.geometry}
          material={materials.material927}
          position={[-0.165, 0, 5.654]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards928.geometry}
          material={materials.material928}
          position={[0.637, 0, 7.419]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards929.geometry}
          material={materials.material929}
          position={[4.797, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards930.geometry}
          material={materials.material930}
          position={[-2.937, 0, 5.684]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards931.geometry}
          material={materials.material931}
          position={[4.019, 0, 5.684]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards932.geometry}
          material={materials.material932}
          position={[-4.736, 0, 5.678]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards933.geometry}
          material={materials.material933}
          position={[2.928, 0, 5.678]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards934.geometry}
          material={materials.material934}
          position={[-0.382, 0, 4.958]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards935.geometry}
          material={materials.material935}
          position={[5.138, 0, 4.958]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards936.geometry}
          material={materials.material936}
          position={[3.121, 0, 4.944]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards937.geometry}
          material={materials.material937}
          position={[2.218, 0, 4.944]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards938.geometry}
          material={materials.material938}
          position={[-3.352, 0, 4.944]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards939.geometry}
          material={materials.material939}
          position={[-0.996, 0, 4.982]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards940.geometry}
          material={materials.material940}
          position={[1.965, 0, 5.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards941.geometry}
          material={materials.material941}
          position={[-0.178, 0, 7.467]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards942.geometry}
          material={materials.material942}
          position={[3.29, 0, 5.664]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards943.geometry}
          material={materials.material943}
          position={[-2.43, 0, 5.664]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards944.geometry}
          material={materials.material944}
          position={[-4.374, 0, 5.664]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards945.geometry}
          material={materials.material945}
          position={[-3.264, 0, 5.664]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards946.geometry}
          material={materials.material946}
          position={[0.665, 0, 5.664]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards947.geometry}
          material={materials.material947}
          position={[-4.027, 0, 5.634]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards948.geometry}
          material={materials.material948}
          position={[2.555, 0, 5.634]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards949.geometry}
          material={materials.material949}
          position={[-1.299, 0, 7.346]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards950.geometry}
          material={materials.material950}
          position={[5.272, 0, 3.631]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards951.geometry}
          material={materials.material951}
          position={[2.183, 0, 3.508]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards952.geometry}
          material={materials.material952}
          position={[3.069, 0, 3.675]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards953.geometry}
          material={materials.material953}
          position={[5.946, 0, 3.675]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards954.geometry}
          material={materials.material954}
          position={[-5.025, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards955.geometry}
          material={materials.material955}
          position={[-2.969, 0, 4.963]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards956.geometry}
          material={materials.material956}
          position={[1.593, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards957.geometry}
          material={materials.material957}
          position={[0.3, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards958.geometry}
          material={materials.material958}
          position={[-3.629, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards959.geometry}
          material={materials.material959}
          position={[0.352, 0, 7.448]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards960.geometry}
          material={materials.material960}
          position={[-1.125, 0, 5.683]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards961.geometry}
          material={materials.material961}
          position={[1.063, 0, 5.655]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards962.geometry}
          material={materials.material962}
          position={[2.617, 0, 4.935]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards963.geometry}
          material={materials.material963}
          position={[0.016, 0, 4.935]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards964.geometry}
          material={materials.material964}
          position={[-4.624, 0, 4.935]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards965.geometry}
          material={materials.material965}
          position={[-0.575, 0, 7.477]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards966.geometry}
          material={materials.material966}
          position={[4.288, 0, 4.992]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards967.geometry}
          material={materials.material967}
          position={[-4.022, 0, 3.606]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards968.geometry}
          material={materials.material968}
          position={[-1.726, 0, 3.606]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards969.geometry}
          material={materials.material969}
          position={[0.192, 0, 3.644]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards970.geometry}
          material={materials.material970}
          position={[3.881, 0, 3.679]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards971.geometry}
          material={materials.material971}
          position={[5.456, 0, 4.967]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards972.geometry}
          material={materials.material972}
          position={[3.984, 0, 4.967]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards973.geometry}
          material={materials.material973}
          position={[-0.685, 0, 4.967]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards974.geometry}
          material={materials.material974}
          position={[1.09, 0, 3.633]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards975.geometry}
          material={materials.material975}
          position={[-0.001, 0, 0.161]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards976.geometry}
          material={materials.material976}
          position={[-0.001, 0, 0.161]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards977.geometry}
          material={materials.material977}
          position={[-0.001, 0, 0.16]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards978.geometry}
          material={materials.material978}
          position={[1.483, 0, 5.022]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards979.geometry}
          material={materials.material979}
          position={[3.508, 0, 5.022]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards980.geometry}
          material={materials.material980}
          position={[-2.043, 0, 5.742]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards981.geometry}
          material={materials.material981}
          position={[-2.349, 0, 4.937]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards982.geometry}
          material={materials.material982}
          position={[-4.178, 0, 4.937]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards983.geometry}
          material={materials.material983}
          position={[1.033, 0, 7.422]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards984.geometry}
          material={materials.material984}
          position={[2.262, 0, 5.657]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards985.geometry}
          material={materials.material985}
          position={[3.591, 0, 5.657]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards986.geometry}
          material={materials.material986}
          position={[4.468, 0, 5.657]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards987.geometry}
          material={materials.material987}
          position={[0.467, 0, 4.857]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards988.geometry}
          material={materials.material988}
          position={[-1.509, 0, 5.594]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards989.geometry}
          material={materials.material989}
          position={[4.612, 0, 3.649]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards990.geometry}
          material={materials.material990}
          position={[-3.247, 0, 3.649]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards991.geometry}
          material={materials.material991}
          position={[-5.777, 0, 3.548]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards992.geometry}
          material={materials.material992}
          position={[-2.458, 0, 3.692]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards993.geometry}
          material={materials.material993}
          position={[-0.625, 0, 3.692]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards994.geometry}
          material={materials.material994}
          position={[-2.936, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards995.geometry}
          material={materials.material995}
          position={[-1.469, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards996.geometry}
          material={materials.material996}
          position={[2.934, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards997.geometry}
          material={materials.material997}
          position={[1.466, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards998.geometry}
          material={materials.material998}
          position={[-0.001, 0, 8.733]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards999.geometry}
          material={materials.material999}
          position={[1.466, 0, 8.733]}
        />
      </mesh>
      <mesh
        geometry={nodes.mortar_and_pestle.geometry}
        material={materials.blinn1SG}
        position={[0, 3.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload("/mortar.gltf");
