/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 slow.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SlowModel(props) {
  const { nodes, materials } = useGLTF("/Models/Cards/Chetti/slow.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Asset_62new_cards735.geometry}
        material={materials.material735}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.Asset_62new_cards611.geometry}
          material={materials.material611}
          position={[-4.197, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards612.geometry}
          material={materials.material612}
          position={[2.283, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards613.geometry}
          material={materials.material613}
          position={[-2.818, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards614.geometry}
          material={materials.material614}
          position={[-1.472, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards615.geometry}
          material={materials.material615}
          position={[0.763, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards616.geometry}
          material={materials.material616}
          position={[1.12, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards617.geometry}
          material={materials.material617}
          position={[-1.7, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards618.geometry}
          material={materials.material618}
          position={[-1.041, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards619.geometry}
          material={materials.material619}
          position={[4.771, 0, 4.685]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards620.geometry}
          material={materials.material620}
          position={[-5.085, 0, 4.685]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards621.geometry}
          material={materials.material621}
          position={[3.896, 0, 5.405]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards622.geometry}
          material={materials.material622}
          position={[0.837, 0, 7.17]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards623.geometry}
          material={materials.material623}
          position={[0.618, 0, 4.899]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards624.geometry}
          material={materials.material624}
          position={[-0.533, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards625.geometry}
          material={materials.material625}
          position={[-2.61, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards626.geometry}
          material={materials.material626}
          position={[-3.866, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards627.geometry}
          material={materials.material627}
          position={[-0.929, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards628.geometry}
          material={materials.material628}
          position={[-0.178, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards629.geometry}
          material={materials.material629}
          position={[4.03, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards630.geometry}
          material={materials.material630}
          position={[1.25, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards631.geometry}
          material={materials.material631}
          position={[-2.305, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards632.geometry}
          material={materials.material632}
          position={[1.612, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards633.geometry}
          material={materials.material633}
          position={[-0.544, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards634.geometry}
          material={materials.material634}
          position={[1.497, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards635.geometry}
          material={materials.material635}
          position={[-3.419, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards636.geometry}
          material={materials.material636}
          position={[2.639, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards637.geometry}
          material={materials.material637}
          position={[5.392, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards638.geometry}
          material={materials.material638}
          position={[3.336, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards639.geometry}
          material={materials.material639}
          position={[-4.565, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards640.geometry}
          material={materials.material640}
          position={[-2.088, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards641.geometry}
          material={materials.material641}
          position={[-0.148, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards642.geometry}
          material={materials.material642}
          position={[0.375, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards643.geometry}
          material={materials.material643}
          position={[0.336, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards644.geometry}
          material={materials.material644}
          position={[3.237, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards645.geometry}
          material={materials.material645}
          position={[2.488, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards646.geometry}
          material={materials.material646}
          position={[-5.085, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards647.geometry}
          material={materials.material647}
          position={[4.771, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards648.geometry}
          material={materials.material648}
          position={[0.837, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards649.geometry}
          material={materials.material649}
          position={[3.897, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards650.geometry}
          material={materials.material650}
          position={[-0.791, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards651.geometry}
          material={materials.material651}
          position={[-0.436, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards652.geometry}
          material={materials.material652}
          position={[1.756, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards653.geometry}
          material={materials.material653}
          position={[3.772, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards654.geometry}
          material={materials.material654}
          position={[3.618, 0, 4.865]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards655.geometry}
          material={materials.material655}
          position={[4.729, 0, 5.585]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards656.geometry}
          material={materials.material656}
          position={[0.077, 0, 7.35]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards657.geometry}
          material={materials.material657}
          position={[0.269, 0, 3.646]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards658.geometry}
          material={materials.material658}
          position={[-1.275, 0, 7.278]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards659.geometry}
          material={materials.material659}
          position={[-5.378, 0, 4.872]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards660.geometry}
          material={materials.material660}
          position={[2.921, 0, 5.069]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards661.geometry}
          material={materials.material661}
          position={[-1.376, 0, 5.644]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards662.geometry}
          material={materials.material662}
          position={[-4.198, 0, 5.644]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards663.geometry}
          material={materials.material663}
          position={[1.318, 0, 7.447]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards664.geometry}
          material={materials.material664}
          position={[4.968, 0, 5.682]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards665.geometry}
          material={materials.material665}
          position={[1.995, 0, 5.682]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards666.geometry}
          material={materials.material666}
          position={[-0.533, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards667.geometry}
          material={materials.material667}
          position={[-2.61, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards668.geometry}
          material={materials.material668}
          position={[-3.866, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards669.geometry}
          material={materials.material669}
          position={[-0.929, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards670.geometry}
          material={materials.material670}
          position={[1.612, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards671.geometry}
          material={materials.material671}
          position={[-0.178, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards672.geometry}
          material={materials.material672}
          position={[1.25, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards673.geometry}
          material={materials.material673}
          position={[-2.306, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards674.geometry}
          material={materials.material674}
          position={[4.03, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards675.geometry}
          material={materials.material675}
          position={[0.269, 0, 3.645]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards676.geometry}
          material={materials.material676}
          position={[-3.118, 0, 4.903]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards677.geometry}
          material={materials.material677}
          position={[-3.588, 0, 5.623]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards678.geometry}
          material={materials.material678}
          position={[3.697, 0, 5.623]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards679.geometry}
          material={materials.material679}
          position={[0.637, 0, 7.388]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards680.geometry}
          material={materials.material680}
          position={[4.116, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards681.geometry}
          material={materials.material681}
          position={[0.901, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards682.geometry}
          material={materials.material682}
          position={[-5.387, 0, 4.872]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards683.geometry}
          material={materials.material683}
          position={[-1.712, 0, 5.647]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards684.geometry}
          material={materials.material684}
          position={[0.751, 0, 5.647]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards685.geometry}
          material={materials.material685}
          position={[-1.053, 0, 5.647]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards686.geometry}
          material={materials.material686}
          position={[1.108, 0, 5.647]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards687.geometry}
          material={materials.material687}
          position={[-1.483, 0, 4.927]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards688.geometry}
          material={materials.material688}
          position={[-2.829, 0, 4.927]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards689.geometry}
          material={materials.material689}
          position={[-4.209, 0, 4.927]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards690.geometry}
          material={materials.material690}
          position={[2.272, 0, 4.927]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards691.geometry}
          material={materials.material691}
          position={[-1.121, 0, 4.913]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards692.geometry}
          material={materials.material692}
          position={[5.025, 0, 4.913]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards693.geometry}
          material={materials.material693}
          position={[-0.178, 0, 7.436]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards694.geometry}
          material={materials.material694}
          position={[2.87, 0, 5.633]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards695.geometry}
          material={materials.material695}
          position={[-4.581, 0, 4.882]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards696.geometry}
          material={materials.material696}
          position={[4.452, 0, 5.602]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards697.geometry}
          material={materials.material697}
          position={[-1.299, 0, 7.315]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards698.geometry}
          material={materials.material698}
          position={[-0.419, 0, 3.6]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards699.geometry}
          material={materials.material699}
          position={[3.353, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards700.geometry}
          material={materials.material700}
          position={[-3.403, 0, 4.932]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards701.geometry}
          material={materials.material701}
          position={[-4.548, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards702.geometry}
          material={materials.material702}
          position={[2.505, 0, 5.652]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards703.geometry}
          material={materials.material703}
          position={[0.352, 0, 7.417]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards704.geometry}
          material={materials.material704}
          position={[-2.057, 0, 5.624]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards705.geometry}
          material={materials.material705}
          position={[2.67, 0, 4.903]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards706.geometry}
          material={materials.material706}
          position={[0.406, 0, 5.624]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards707.geometry}
          material={materials.material707}
          position={[3.268, 0, 5.624]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards708.geometry}
          material={materials.material708}
          position={[-0.179, 0, 5.681]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards709.geometry}
          material={materials.material709}
          position={[1.466, 0, 5.681]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards710.geometry}
          material={materials.material710}
          position={[-0.575, 0, 7.446]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards711.geometry}
          material={materials.material711}
          position={[0.239, 0, 4.929]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards712.geometry}
          material={materials.material712}
          position={[4.447, 0, 4.929]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards713.geometry}
          material={materials.material713}
          position={[-3.891, 0, 4.936]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards714.geometry}
          material={materials.material714}
          position={[-0.645, 0, 4.936]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards715.geometry}
          material={materials.material715}
          position={[-3.332, 0, 5.656]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards716.geometry}
          material={materials.material716}
          position={[-4.874, 0, 4.936]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards717.geometry}
          material={materials.material717}
          position={[1.927, 0, 4.905]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards718.geometry}
          material={materials.material718}
          position={[-1.199, 0, 3.543]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards719.geometry}
          material={materials.material719}
          position={[0, 0, 0.13]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards720.geometry}
          material={materials.material720}
          position={[0, 0, 0.13]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards721.geometry}
          material={materials.material721}
          position={[-0.002, 0, 0.129]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards722.geometry}
          material={materials.material722}
          position={[5.412, 0, 4.991]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards723.geometry}
          material={materials.material723}
          position={[1.033, 0, 7.391]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards724.geometry}
          material={materials.material724}
          position={[-2.923, 0, 5.626]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards725.geometry}
          material={materials.material725}
          position={[-1.788, 0, 4.906]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards726.geometry}
          material={materials.material726}
          position={[-2.011, 0, 4.826]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards727.geometry}
          material={materials.material727}
          position={[-4.932, 0, 5.563]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards728.geometry}
          material={materials.material728}
          position={[1.188, 0, 3.638]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards729.geometry}
          material={materials.material729}
          position={[-2.936, 0, 8.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards730.geometry}
          material={materials.material730}
          position={[-1.469, 0, 8.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards731.geometry}
          material={materials.material731}
          position={[1.467, 0, 8.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards732.geometry}
          material={materials.material732}
          position={[-0.001, 0, 8.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards733.geometry}
          material={materials.material733}
          position={[2.934, 0, 8.702]}
        />
        <mesh
          geometry={nodes.Asset_62new_cards734.geometry}
          material={materials.material734}
          position={[2.934, 0, 8.702]}
        />
      </mesh>
      <group
        position={[0, 3.217, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={14.443}
      >
        <mesh
          geometry={nodes.group329809162_1.geometry}
          material={materials.mat14}
        />
        <mesh
          geometry={nodes.group329809162_2.geometry}
          material={materials.mat18}
        />
        <mesh
          geometry={nodes.group329809162_3.geometry}
          material={materials.mat20}
        />
        <mesh
          geometry={nodes.group329809162_4.geometry}
          material={materials.mat15}
        />
        <mesh
          geometry={nodes.group329809162_5.geometry}
          material={materials.mat8}
        />
        <mesh
          geometry={nodes.group329809162_6.geometry}
          material={materials.mat17}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/slow.gltf");
